apiVersion: v1
kind: ConfigMap
metadata:
  name: ids-backend-config
  labels:
    app: ids-backend
data:
  VERSION: "1.0.0"
  LOG_LEVEL: "info"
  # Tunnel configuration
  WAIT_FOR_TUNNEL: "true"
  # SSH tunnel configuration
  SSH_HOST: "50.28.87.147"
  SSH_PORT: "522"
  SSH_USER: "root"
  LOCAL_PORT: "3306"
  REMOTE_HOST: "localhost"
  REMOTE_PORT: "3306"
