apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-backend
  labels:
    app: ids-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ids-backend
  template:
    metadata:
      labels:
        app: ids-backend
    spec:
      containers:
      # SSH tunnel sidecar container
      - name: ssh-tunnel
        image: alpine/socat:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache openssh-client &&
          mkdir -p /root/.ssh &&
          cp /etc/ssh-key/ssh-private-key /root/.ssh/id_rsa &&
          chmod 600 /root/.ssh/id_rsa &&
          echo "StrictHostKeyChecking no" > /root/.ssh/config &&
          ssh -N -L ${LOCAL_PORT}:${REMOTE_HOST}:${REMOTE_PORT} -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST}
        env:
        - name: SSH_HOST
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: SSH_HOST
        - name: SSH_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: SSH_PORT
        - name: SSH_USER
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: SSH_USER
        - name: LOCAL_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: LOCAL_PORT
        - name: REMOTE_HOST
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: REMOTE_HOST
        - name: REMOTE_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: REMOTE_PORT
        volumeMounts:
        - name: ssh-key
          mountPath: /etc/ssh-key
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      # Main application container
      - name: ids-backend
        image: prodacr1234.azurecr.io/ids-backend:main-53f0922
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: ids-backend-config
        - secretRef:
            name: ids-backend-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: ssh-key
        secret:
          secretName: ids-backend-secrets
          items:
          - key: SSH_PRIVATE_KEY
            path: ssh-private-key
          defaultMode: 0600

