apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ids-backend
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: ids.jshipster.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ids-backend
            port:
              number: 8080
