apiVersion: batch/v1
kind: Job
metadata:
  name: ids-init-embeddings
  namespace: ids
  labels:
    app: ids-init-embeddings
spec:
  template:
    metadata:
      labels:
        app: ids-init-embeddings
    spec:
      containers:
      - name: init-embeddings
        image: prodacr1234.azurecr.io/ids-backend:main-65f1528
        command: ["/home/appuser/init-embeddings-write"]
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: ids-backend-config
              key: database-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ids-backend-secrets
              key: OPENAI_API_KEY
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Never
