apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: loki
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      initContainers:
      - name: generate-file-sd
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Generating file service discovery targets..."
          echo "[" > /etc/promtail/file-sd/pod-logs.json
          first=true
          find /var/log/pods -name "*.log" -type f | while read logfile; do
            if echo "$logfile" | grep -qE "(kube-system|kube-public|kube-node-lease)"; then
              continue
            fi
            if [ "$first" = "true" ]; then
              first=false
            else
              echo "," >> /etc/promtail/file-sd/pod-logs.json
            fi
            echo "{\"targets\":[\"localhost\"],\"labels\":{\"__path__\":\"$logfile\"}}" >> /etc/promtail/file-sd/pod-logs.json
          done
          echo "]" >> /etc/promtail/file-sd/pod-logs.json
          count=$(grep -c "__path__" /etc/promtail/file-sd/pod-logs.json || echo "0")
          echo "Generated $count targets"
        volumeMounts:
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: file-sd
          mountPath: /etc/promtail/file-sd
      containers:
      - name: promtail
        image: grafana/promtail:2.9.2
        imagePullPolicy: IfNotPresent
        args:
          - -config.file=/etc/promtail/promtail.yaml
        ports:
        - containerPort: 3101
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: positions
          mountPath: /tmp
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: file-sd
          mountPath: /etc/promtail/file-sd
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          capabilities:
            add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: positions
        emptyDir: {}
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: file-sd
        emptyDir: {}
      tolerations:
      - effect: NoSchedule
        operator: Exists
