apiVersion: ENC[AES256_GCM,data:DGk=,iv:1ZdCxMrE8VA6hMgKYHF8zTKrDbM8fzgz6932CIOCJ2s=,tag:lNV/en9u5NbY/URHSVvTag==,type:str]
kind: ENC[AES256_GCM,data:FMvlOkU2,iv:EWzY1LDh4oKFtUjhkODcYqL9AJbUzGChLZbQxWnWZwQ=,tag:1a3aKYiU07zdb61ov2yoYg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V2ItAgRQPZKx,iv:aLnsl4hg5TdVSKgWDDAutr3NmbAdfK8wVPcbZkfslfw=,tag:CG74zPmMbAGQFAM0f92pkg==,type:str]
    namespace: ENC[AES256_GCM,data:e1ayZA==,iv:/NfFg90+OOQzsrdV92gjuYArNYKZhyHd0E/RMzhaYGQ=,tag:gCGrNhTV6+/6S9/VYQvNLA==,type:str]
type: ENC[AES256_GCM,data:JJhBssdN,iv:gTPENxSquAoSXk/sPXif1FrAmmbNJAwSmcD4b1hNJcU=,tag:wogI3ulgFQaWeV6aBxcq8A==,type:str]
stringData:
    auth: ENC[AES256_GCM,data:DrbnSPFGvo5RAIv4jhlte7CktnT/YFUtAl8RTrhkyIudQbcs6RR8eebITg==,iv:tLMc0niaoiQW/cN7y5rj6Ik9uByDf3Fzu9QYpaMj/yU=,tag:Yor+laI9gExKrhlf0ZFZVw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SEkzeU1sWEZMbnJpZFBZ
            cDI2ejZXanc0Z0p6b1RkMzE5bDc3Z2dFV0NjCjdjajIzZEJRSmdjVFdaQy9VdTE3
            aW1TSmMzZFFpd1NZT1h1L2RKZk11NEEKLS0tIE5lWjNYRCtpMDZQczhKMXVPSFFR
            MDEyb0xsMDZnMDZEYzZtaHNJK3ppT3MK8CqabP6gpAcCMJ/mL+AEcs60op79JTT1
            Aly+aqyxWq5Wz9YJLKCLBzVMujWiHaExeGQJsayY8XcueXtQAmttjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:09:54Z"
    mac: ENC[AES256_GCM,data:qXiVMxHvqAyq77g6iFVkM8P5WOJx5U7gYzVoKhcL85rApbt49aJ07XKOKBpBMz+3cMZhUSCl2UMKVy/88U7qSR29mI/smfmEELxBLq3flphlYUD/NHa1CnM7TlAYblnGa8Vlyq+E+T5v/J8cg79d0L/Dbuwk1v5X7NhcfoUxA8Y=,iv:810iAz90VrmqSr0TB3T4Bo50mlojzVyt3wZKERmtQlE=,tag:qViIiLdXTHcMb91cqI4uxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:8BQ=,iv:x9F4VZl5IuisWVPchxUscwUORlP2Awd5vKFuypCQk8s=,tag:tDYxp0+4zOLrm1FUHNkXXg==,type:str]
kind: ENC[AES256_GCM,data:zBXw0r3P,iv:zPIHeitx4dTzUqidJFYt47X1y6Z3mRstvslfziaOEd8=,tag:9H7RFB7VDQMs12LbjRssMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GNU+YnLJuUGbzl8Mip74xKP5,iv:Qidnxqm3yRjR0zB6m9xEg9p14o0dtAl+TWQHji0ZxKI=,tag:Qitw4J9Zi2LYXoS7Fvo+Hg==,type:str]
    namespace: ENC[AES256_GCM,data:lLiYeg==,iv:Jphn4cunY2hP2q3WtOAOG8JcWGmuCJERgDbRjIsCIC8=,tag:pd3RXds5I3a7l4i199TZUw==,type:str]
type: ENC[AES256_GCM,data:JVapN1Sh,iv:SivoFsKdNhJohPbAv3pU0ZdO6Yziz4sqn6uoFnThG9k=,tag:Mq/NW/mQB65GZ2/wY2LH9A==,type:str]
stringData:
    account-name: ENC[AES256_GCM,data:frc2G75XcPPJMwmtwuMRP/JvNA==,iv:ISa2KYeDX1PhDEtqzhooh385+OAoEbpeVMVQWsshLxU=,tag:Ysfh7O1aO+IScRUB9nchdQ==,type:str]
    account-key: ENC[AES256_GCM,data:IsG2mOdEKEG95YmtVAZEdjfYtsqyysGno1bnTsY20R/lZjqzzl+Hlx/FIwojWJOVHmhf8GE6Ls/LffK+shWS2nwPWCH00MtqYB5eWqryEgQEQQN2XhiDAA==,iv:CI3f+BEphkhlTplwu0KpLH6Npcev8iehsUjeIwk6Mrw=,tag:Dmz9lX7ibZseRpU/8ZbTPQ==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SEkzeU1sWEZMbnJpZFBZ
            cDI2ejZXanc0Z0p6b1RkMzE5bDc3Z2dFV0NjCjdjajIzZEJRSmdjVFdaQy9VdTE3
            aW1TSmMzZFFpd1NZT1h1L2RKZk11NEEKLS0tIE5lWjNYRCtpMDZQczhKMXVPSFFR
            MDEyb0xsMDZnMDZEYzZtaHNJK3ppT3MK8CqabP6gpAcCMJ/mL+AEcs60op79JTT1
            Aly+aqyxWq5Wz9YJLKCLBzVMujWiHaExeGQJsayY8XcueXtQAmttjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:09:54Z"
    mac: ENC[AES256_GCM,data:qXiVMxHvqAyq77g6iFVkM8P5WOJx5U7gYzVoKhcL85rApbt49aJ07XKOKBpBMz+3cMZhUSCl2UMKVy/88U7qSR29mI/smfmEELxBLq3flphlYUD/NHa1CnM7TlAYblnGa8Vlyq+E+T5v/J8cg79d0L/Dbuwk1v5X7NhcfoUxA8Y=,iv:810iAz90VrmqSr0TB3T4Bo50mlojzVyt3wZKERmtQlE=,tag:qViIiLdXTHcMb91cqI4uxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
