---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 10
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{status=~"4..",service="ingress-nginx-controller"}[5m])) / sum(rate(nginx_ingress_controller_requests{service="ingress-nginx-controller"}[5m])) * 100
    successCondition: result[0] < 50