apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-demo-be-service
  namespace: demo
spec:
  selector:
    app: argo-rollouts-demo-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP