apiVersion: ENC[AES256_GCM,data:rgE=,iv:GQ5GtOI31D8DT9hQwLpUTTKP+r9cRj184zzkcDR2OtY=,tag:P0Ye0NVYD0SCu9RCiXVuRA==,type:str]
kind: ENC[AES256_GCM,data:UKpE/CZg,iv:bZ+yQH55gATMuC2viuLrIxgJUEJgQMzTXxMtjLEpzq0=,tag:QK2/Jg15AAva9939LhWGOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w6GZPpgYVnYxMQ==,iv:/FegzTtM9dOYE+A4ic010TMo8ITILQdlWYnlPM0oJ8A=,tag:bKvc4Qsu2SSbCfeGOlf8gQ==,type:str]
    namespace: ENC[AES256_GCM,data:63+wVg4=,iv:3Ejuw89kcAI6DRmyQeb8I8nhNTjLlgWcmZvPCYCfw1k=,tag:3wCiZCFYf1AZyQIpAhRvmg==,type:str]
type: ENC[AES256_GCM,data:39Ke+/0v,iv:FE6VcG6phCPJ5F1bGmY1dvSypi9XNYkpAHYmXTvG/+Q=,tag:ZoANzMqNU1KOYwFYSFYL0Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Yz8KSnDn,iv:wafzqrQzcKYGipLk9DuXsqTeqESfgjt43zpL/y89Y5o=,tag:/rCWohffhuNsPz/rp4Wysw==,type:str]
    password-sha256: ENC[AES256_GCM,data:AaL0f3qca8JTUCFuJmB/BkZEB2Plb15PU3gpA5wVKMbsdXRMvfXs+uMv+Bm/3LCfTTjF/1GZC5h86s8lKtz/3g==,iv:TxnrJImTdZ0xhpwG6BCqsZ9O1dG8xRKvU0uqxmPRwvc=,tag:la/XpfQgyzce1/lwwuGU5A==,type:str]
    google-maps-api-key: ENC[AES256_GCM,data:wxCGnTq2r5/HOCvi1vhxczq91z8+lO3nlq60bcDkjtpGGWUZoZUY,iv:mmXvyYn2qXIP5nap/SEhfFRseUmkmy15Nc58trY8Li0=,tag:w40un/U6BSV/vUOENoNwcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQzFicGNWczBONCsweFF4
            ckN0bmRtREQvOEtPbG56b3RrS3hkTzh4amw4CjR2QmQrSXZzUTJ5ZDVDdG91QVZi
            QTdRTjAybThHYmZUR2xlNjM5SGFPLzAKLS0tIG5xMHlyWEVJeVVETFdST0ZlNkRJ
            cUhPSnJRckx1dUUyNktMOHRiMkxnYjAK4U36ZQ2dwdbUnF8ehjxtudL7f8uHlrpV
            L6kAqXAOJamFmR1ehwE1gt5ZCPJmIgmL+u6chc4dMhsX7qqoDlTzsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-09-06T16:31:04Z"
    mac: ENC[AES256_GCM,data:6kIWtSlw7Cs8iyZza30yHt79RKkUITxMNGnzn4cyAza51EBfR5fVFouGP3E6WjVXn/6mDjvfD92LlzkndYD6lBI5nNt8ZCtrS5MWTTwLkT1OABXkKRRARjWE8q4+wNj280S/vuNglVuELjLi+n9W3RRl2Ky2LSXzs9IXcIbVMsg=,iv:jaE4prqjgsQpL+mbam5J3befUjuUyfjH72wNQRRRKOU=,tag:czzu6lN205NXJJa2r2g/Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
