apiVersion: ENC[AES256_GCM,data:95g=,iv:YT/F04zeqP/hLuumWmf/xV/wcwzUbaYhZO7CuBYpeK8=,tag:H4ueXkz3VP9oKYfzL7GHGg==,type:str]
kind: ENC[AES256_GCM,data:HE/n7y2e,iv:aVkoE+ohAx9jO1Km0V0322LCiA6WPVami3htwqHHJGE=,tag:paVG+FW3hkOHjSvJYBsN+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BvyNsqCZg3jBeQ==,iv:SBI4chJH2RSk+ld3KwNLetoMf8rIkK60+lE8mXLWggI=,tag:1yfABrtU/9O7qmthZeKFgQ==,type:str]
    namespace: ENC[AES256_GCM,data:tbOroXE=,iv:mLge+v3tJBFlbDShiGgSOVfeyrA7varfd9Y0h9XvuO4=,tag:1h5uYCWmADmOAFGt4EKUdg==,type:str]
type: ENC[AES256_GCM,data:P9fmfDvh,iv:7xKXQ29NpRmx2vxn/WfikHMYkck74ooY0gAGBsSUgf0=,tag:mR1g1NSy/6vCtwas1QfCHw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:cwTQcW7t,iv:tsLTMBzYIVXqcOwPh2nKeFWW5roL5TC1EG+fL5prp6U=,tag:YqSaqUYOdJFlZZykjwG0GA==,type:str]
    password-sha256: ENC[AES256_GCM,data:YNIT+8bJAkzqYQTTGma5yoL3+ta5YisbGjIDoJ728zUIfYsF7Eu0g/qgovf6QJNoMqFh1tmLlbQsjxHZxKakGQ==,iv:36nROx+2hZGuUoFj4tE0Ij5P/Zxleb/lz4DPy9ZZbcA=,tag:hUX3C8RRvZ6Nyp8IMlKNZg==,type:str]
    google-maps-api-key: ENC[AES256_GCM,data:dtxV2f5fW5FRltP7rd5so/6nU5r7f2HeEzVbbNfMVL9DyLaxd9mT,iv:a61MjRpblRSfn8ijFdqkZH8h0JmyVKHMGjrbU4pw8EA=,tag:9ziQ+mkgdhCOxUE+xpDVGQ==,type:str]
    google-client-id: ENC[AES256_GCM,data:dFYuCDJ8apdH3d5IJfTI2vpbA1Iung9nRJbLolrKwtyKzQcnh0CNEwfgKPPa6rxSXyTVnCH8HZXw+DoqyLzfB74ccJQtsjU=,iv:eupc0TkhnYyxMqX0nEbbSvlH7J4kUEFj5SvMBPl5oyg=,tag:XD9xGZZs5pyO00JJj6kQMw==,type:str]
    google-client-secret: ENC[AES256_GCM,data:bR/aJsivlDJ8sptvTAzaWpZBh6XGekF98swIlpjfBy/zAKU=,iv:Pr2vRGthCVHf5UCt8xQ1lS6u5pLcvNxmHd1K1+MsHPw=,tag:sdlEk6myQHSyCiBVtxYMQw==,type:str]
    session-secret: ENC[AES256_GCM,data:QdcR8FHq8anDhXMyH2BZ13u+GNUXpbDhFCsuDR2zt/NHQOa+0XKKGvxQh016w7XmxQzQISRLPWHd15WYCn4Hqg==,iv:MU8sqyOazzx1pJpf5YYlm7mrlNXGktuktEEyxA/1PZ4=,tag:YsvWQdjc1RiO7A2FZSjOfw==,type:str]
    allowed-emails: ENC[AES256_GCM,data:1D/3qSKxO90ONATcHQgo+8U9s/mGTzjAyZ0QpR6awWgsoPBc7T97ylmhy7un1uWEhVZuOlrJfegB4O3bYFvrFP3IoKR8nK/kXV1AyddWm/r3v9PSglbGVeHb0xBhUBizFdV0EYHGouFjBOXXExacvBLjr4gO+Nu3oA8oB4708In0RDd227sHQluyjPZnpCgdnURQtJM5130jPpQ35kINbgHZCMfs8lqVgNavP+6HOFuXMMwZac14Aq3wkd3SzCzuCOMMdtHPAGqwiXoLrLSY,iv:YAN+qPcwYwwjBudYm/nc3nvnYRbspiVTcKSy4QhrWaE=,tag:3SLGVu0mzrmW4nv2bpq0IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY2R6MGNIVlc5dTFjU2w1
            SUF0cHBzait1RUlZdDkrWkJBQU1hSGNEeTNnCkpvWThSWnJ0TitvL2F1aTNrdnl1
            R0FIempJTTRjRWhKMXRLYXNxZVF2RncKLS0tIDg4M2tDVXBCWHNEZ25mNjNRQStk
            TmU4YTkyMGhPcm5SUVhOUTQwbU53MHcK1zNdYpjyeDyTaWCiUR5jAaoI8e7d2yn5
            MhWKsFWS4bAuVnPi/1ZTgo0miydOv8PvCFl7s+ZNt2rHL4C+fUy+DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-09-12T07:51:20Z"
    mac: ENC[AES256_GCM,data:zWyGdSMX992jdRwVCRIDim1MZrWdPDiOgQUZ6wtXMqBnwWuzH6EPYUN9JvNTlwthYTg6+gZ7tdw36vlFY1o7VCMTX4vo2osKqZ0WSS5zk2pNYPW2yIecR7TIU6nc+BhoBQmXA5ftYPweO75VfvDwuGIxAaX3uFab9qDuKX8JrfU=,iv:ijMINRrbPBaM+WpGYVHnvPQiG4TjeW1JzHpMV8Mb+jc=,tag:67sObZ1P0BDkvV7T9Qin5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
