apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnson-backend
  labels:
    app: johnson-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: johnson-backend
  template:
    metadata:
      labels:
        app: johnson-backend
    spec:
      initContainers:
      - name: johnson-backend-migrations
        image: prodacr1234.azurecr.io/johnson-backend-migrations:70c8f5e2adf0af136ce7b05beb46006cfb8e27da
        env:
        - name: JOHNSON_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: johnson-backend-secrets
              key: JOHNSON_DATABASE_URL
      containers:
      - name: johnson-backend
        image: prodacr1234.azurecr.io/johnson-backend-migrations:70c8f5e2adf0af136ce7b05beb46006cfb8e27da
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - configMapRef:
            name: johnson-backend-config
        - secretRef:
            name: johnson-backend-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

