apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: johnson-backend
spec:
  ingressClassName: nginx
  rules:
  - host: johnson.jshipster.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: johnson-backend
            port:
              number: 8000

