apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - bootstrap-configmap.yaml
  - tls-certificates.yaml
  - statefulset.yaml
  - service.yaml
  - bootstrap-job.yaml
  - optional-tls-reload-cronjob.yaml

generators:
  - secrets-generator.yaml
