apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/name: shared-postgres
    app.kubernetes.io/part-of: shared-databases
