apiVersion: ENC[AES256_GCM,data:oi8=,iv:/QwTXxdt9L3i+jXwrDdtu+kmdWwWhUNv08s1p/wdckQ=,tag:QYZ4ZPo88dSNj70HjEvhrA==,type:str]
kind: ENC[AES256_GCM,data:KmvUfQyY,iv:v1TIokfu8rbveOOh/18fv4uFkxFJ2D+kHXQkENUYBhg=,tag:dDs9yxiTuW0kGBqeVq0rTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GMZxm2+7Q99kPFx1zwEb8ltqsfhkl6r6Ec4=,iv:M6+C9ymNCTyFHWtgfs76luaChyxhGh52/jt2zjWWqCk=,tag:Pjw1AvwUgNscVmZFdtrQMA==,type:str]
    namespace: ENC[AES256_GCM,data:ml1gIPxkbN0=,iv:4uQFgBsG3s+UzPqLIzVewq2jEb5jDu7R/PCaexgcEHQ=,tag:5WhPC3cCDmpqYqV150QKaw==,type:str]
type: ENC[AES256_GCM,data:zTzg92rj,iv:IV/4X/0l9qdcWZmFGlzNlvngufPZnxG0qLIfzYLYwCo=,tag:TCt/RBwCw7W9IeM3Khs7DQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:fBMlK1EvyFGH9/3gf3Cw6QS8XvYyiZ7Bh/HmNRBj1flW/qKAfvwTSqlxM91ce1qsXYpB2MNve3WaOrqCaOZz1g==,iv:HEr6weZ7taaRxYjebVvHkiUv7bxhsBAfhMgcPiowDVY=,tag:AX3fg6WvREYpMfsdqckTUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bGxtNWtrU1BzZm05OE55
            Z3dDSDR1b0ZwSzQxNHlibkRhMm93SndDVG5RCk1yT05rREovZlVGTVBxZUJMcjZB
            RUt2ckJqbUhPZkt0bGhTR0t1RlU4R2cKLS0tIEZ4V3V0dWxJZkJwSWlzQWtUYW5D
            bU41M1UwT3BBdU1NL1RMbENnaGJYQW8K3XlecvgURkJGwl/kEoKT4jTyO/mit1LL
            pVhIhHO/K3Lu6BDxVDscML/xfXe9YqYcdWG3LhRx7ANq6cGoV5TtZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-10-10T14:22:27Z"
    mac: ENC[AES256_GCM,data:ZPEMSxxn4vRU+l3CayBEAA6NkBm26NdFTFNGWtwelWB81bAhzldoa319a8E5gqlWpSg1MqsmQzkCQunx47lFf3zTWogtA1N50Yv+z/iUXSrnsf5IhTWcNCVtSVMKqrW11hEiJiu8uyO+PJqMRkNYH1nju+tu4mtTPqQGsGaXkxY=,iv:jwNn0nqGYZwzyhs63x3YTtnqHtg4DZb1cELpeClI2p0=,tag:zJeCDCq2qROwfsQMLj9J+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
