apiVersion: ENC[AES256_GCM,data:5OI=,iv:lZAbeaLFF0ZFqygsfeLCNGOLw8PeX+ditU9/VpigGiY=,tag:rY9eoaaYCoL+TkhImplMcQ==,type:str]
kind: ENC[AES256_GCM,data:WT8mOVvs,iv:YIWopF0l1+uwWWRPGXnXfXQMnb73UPQgCkEVYpdo+L4=,tag:Wfp6VRTrF4q6VFOrkI+JoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W1pxbuvZrnVvheH0xz+y17q4lXuB5J4=,iv:Y/Xxlb1mdZ01y2+7RW/Vu31O0vcyj5nr5SEq20FsIcY=,tag:xTroi49lv8TaeKR2RIYVVw==,type:str]
    namespace: ENC[AES256_GCM,data:BBud1Mp1N+Y=,iv:20H0EwB/JkVQ18P12GFsGQ9HZxSUhHHwybwksUHVDEc=,tag:CIT21fqmh02g5qIs9c5EmQ==,type:str]
type: ENC[AES256_GCM,data:Fc3VgXwl,iv:O37JXv6JaFNVwkoaL6VsNLam2Tw3dctXblCsVSe67T4=,tag:ycBsfUng4tvCi3oS35adQQ==,type:str]
stringData:
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:6FGhIpDexkXa9I1Jeq607JztEa+ki1ghh4jXquAx3mgu6g9TIh/5wxql9nf9qWoaMogn3TV6mLbRi5usGZGWDw==,iv:51SzZSkt52Icb77SBGA2/QtT/nXMdkKPKoRUnvY1Qyw=,tag:CCRrOJkBGi34XmERfveDfQ==,type:str]
    ANPR_PASSWORD: ENC[AES256_GCM,data:mFxRcCLvwBadYI8diL5dcyx8xwOUYFFdHhnk81toU/g53BwrqL2WIWwNP8NahplOQ5ZPsU0FvOgnLhCmIUyv8w==,iv:5PE2t4SV4Bj7gxhUH2LZ2wp84wiAKu60F//+O5tvWy4=,tag:MCXmakTNA+td2p/cNq3rxA==,type:str]
    ANPR_BACKUP_PASSWORD: ENC[AES256_GCM,data:XUHeEhxq1UpATcj9x64mHf3ZDHsnhE/0fK4S9dQaTYRfN5GIG0cicsRcaoaczFzWXnBv9HeTE9vOZTHKkvGmgg==,iv:KrSIbUFdjw6/Nsx+8cFrkQtDkCesUNCC521uNfLnSpk=,tag:cSjAK8dDDMGMFmotyz0PvA==,type:str]
    ANPR_REPORTER_PASSWORD_HASH: ENC[AES256_GCM,data:sB32WTlxcREzATMccv3GW5Q1ACZrouQBrSwc0YVYQO1JMrIR5UEWMYkg5UzULN351Ili0ojKkHlTrNr/Q936nJeQVdamv5Ine7aEd5KoYDtml0dww7oLy+DB/yHgN/And2cFUTDUKpqp0ZYXbwkpbdk6prl9xJ/tXc9Ss9iT235Ky+NqGQ==,iv:7BOaWNHpUeyrsq4/IK/4LYGgD3Avix6iWmo2ulH5slI=,tag:ShiVmy82TIxl6A+wtmwuYA==,type:str]
    BLUTAG_PASSWORD: ENC[AES256_GCM,data:gkVQxrVch7Dpn7JnOLQTwFMxM9E=,iv:Ea2EFv13tygRbwOq3SyJ26Kl2X/w6pVNkqEj/Xekqek=,tag:Y53e8vq45IaPhAeTbISbYw==,type:str]
    DIRTBIKE_PASSWORD: ENC[AES256_GCM,data:SS+rCYs89kFGLNbDjnRMVux93fjeG6gxDQ==,iv:rwJLCtThRFUveMb4Q67RC4vQT/15O+5INjgPCsuQIGI=,tag:ebAZffGSNrwsPi/GQQvG4g==,type:str]
    HASADNAA_PASSWORD: ENC[AES256_GCM,data:f6hsDleujNA=,iv:v87ZitV8034ggoy5n+f/a7FBeZt+yQlRsL0LzEEyMDA=,tag:UbeKA7b+8EwjYLMPEuLw8A==,type:str]
    IDS_PASSWORD: ENC[AES256_GCM,data:Wv6aeUqhA270eJSfYmzXJud1IKaopcCbfVgBBg==,iv:BmYKLjuZid8W3JKeYMK1qzoO9KuvIlwqM803Gy4zql0=,tag:CW5dI+eimQLD1ykgsqK1zQ==,type:str]
    TRAININGS_PASSWORD: ENC[AES256_GCM,data:0ZftXh5TtSNil0BVHdNrYE1FOR3NzucjBSnbb+8BZvc=,iv:eXL7pLSxvLBLJiMldVkKsqmfx0FJ+vCgKkvDmXliYYg=,tag:m6fkt/d1vBITWW2JB9PHig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SHpVaExmcHhtV3pSM2pD
            ZU0vdGVVQTNLMnI2Y1AzaXkva1hHalNVWkNnCldtY0ZmOFcwL3ByVlN2aUJwK291
            cGplalY0ZG5JTEhpN1lRcGZ3azNySkEKLS0tIDFaTlVFejlqajJWanUrTzdJUXQy
            MjFFUk1seDBsY3JIdGtVV0FiN1pCcVUKZ0UVB1zdDVICJo9pjrvmmismAlyhveQo
            OQHJxkLf4zBX4AXm7H0zkFVH8pBvjh1CF5/g5B3Hu40FU9zrFxq58g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-09-01T05:31:12Z"
    mac: ENC[AES256_GCM,data:An4hMNjmQ6KCREaqtKEAaVSBEhw7GxLibGblLi2BXJjSYBsX1LCCImLUV8cE8C1L8Z4cyp5XlfQ5PrPX5tGNUTZ/lTtrdcMpbUFTeCgeW9DpXb1Ro335ZUMGOicAsH4RQiZoHjQl+cucbRhp3B/h7DqhL8molhwaFQzyZ3oB09Y=,iv:Z0Sv3UPvCa1ibOxvA1vhefDZT5SzGk+rGW2w+V/Bqyg=,tag:yXUC8ADDPDSXV8HC0G312Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
