apiVersion: ENC[AES256_GCM,data:0OE=,iv:6ql9Gpk4SXaJ8AGb9cuNi9hHYcEd4cuGlKVsiZpvdFg=,tag:ALgFXxXkEoRwXteMQLlD9Q==,type:str]
kind: ENC[AES256_GCM,data:ZtusMgn2,iv:bpcaEX7Q86BkRTBHR0ret01QOSUg1he38Ep4VzpTTsk=,tag:KnY4P8pNNwPzN4hIM81o2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3rY1TupPFpSWtrucSmjDGIg=,iv:+awq6cAKrV6WoLHKCZY0n3QAnrR4egpLs0c+eqhnzI0=,tag:gDM0Pjk5tRgz4vQOW4obgg==,type:str]
type: ENC[AES256_GCM,data:Z+0qwEaR,iv:QR/XoAREiteHHh4EdKVzPtGUpKcaaAZ4ysa4+yVrXPM=,tag:taKyjMDOZbpQBN7hm/COXg==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:On/bYSioiYanE9gf7rX++bnwByKAQgGfKQC82ZM7150dkfWnMaDh1cqcJYoinC/IHOmtQuxlB3TfXA==,iv:fkhlVz6WjTRtIn1+Q5UTWaRb22OCeyMzHrONaJr/+Qg=,tag:qB2WX0MV3nXjN2TR9pIbKA==,type:str]
    SYSTEM_ADMIN_EMAIL: ENC[AES256_GCM,data:QrBdE/l0854mVhZ0dt4P,iv:QdLH6p2Avf/g/aqAXuXxbkeXNEW1vmWGUv+gMgQughA=,tag:Gy8MTKwtiB++h/lt18mbNw==,type:str]
    SYSTEM_ADMIN_PASSWORD: ENC[AES256_GCM,data:cQxeVTJO0baEshHWS4ce5A==,iv:ExMSdckx1xSEVNow3/FsGcVkCXNiTHc+jcZ5OBDVck0=,tag:bd99hmPU8Wxk00S7GwXQlw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV3hhNG5WUTNReXAxU1JO
            eXJwZi9YRUFYd1paUlQ0SHNXaFBzN1VrL0ZNCjhuUEVWZlVlcTB4Ukl4UVZTOWFD
            Sm9zcTZpQ2dVN09PNGtaaThGM1U2b1kKLS0tIEpJZGlHdmUxSUkrUi9hQTJ6OEVs
            VDgrL3VNbmVkUUkxQVJNVGdxbGltN1UKVwaeBy5v1cTHrQvF6XwRUB5Ru7J20aRw
            4MHEFwkdG3iGeACn5KwDcp1zoa5Py8v3so/C+C+f2US2T/araHlUHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T13:55:31Z"
    mac: ENC[AES256_GCM,data:AzZevWvhhMG/JIzCFlBbw0/qIi8FjrlpLEOtSJPCSA2YG9LQINRI/ZKK+WIcZim3G/1SpOBA1sOTVZjrFO9wKIB+tcuj8jp/zeqjKw3gIa4BAh1b7n7GqmOi57h69bZ/kzvlSNbwkjafYgvecn3n88H2qS3bxaVnFSIqbtiHoRc=,iv:Vejmildqtex2yekqY1PFWCvIneZIoPlGQIuNmPJoiUQ=,tag:64Z5LCkG0dfM8I2wwPCfkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
