apiVersion: ENC[AES256_GCM,data:8G0=,iv:IRBbG5gXAxE8VI5EmhjQyGOvtnowyAP8L7E2TwuCWDE=,tag:wTTpdWj1KsrCt/LStWop2A==,type:str]
kind: ENC[AES256_GCM,data:TslWuaQO,iv:VX/+4iNXtDNp6g0tY5ubDCOZv062bPgj/kkZOWoUAMw=,tag:NHMMyEGH8yCp6MVaRZ3hLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QAefV9dwoQFBXRf53uL9Woc=,iv:3V4MVjXgTRn2t8DM/4tq5QiFH9XZ0xMyLSu/5/WN2Do=,tag:wJAlLiTCGw7LSfAIHmoT2A==,type:str]
type: ENC[AES256_GCM,data:PlQ8bnJZ,iv:VKUNKkLqoJwJGYtkvbqeBlzadKi1QK3p9voCd0eUkgM=,tag:LI97jRP8Kpy4iJTG6QJZYg==,type:str]
stringData:
    ACS_CONNECTION_STRING: ENC[AES256_GCM,data:80s09/WCxc6AdeoG3PJuFcoYbEDtiDkQn0K+7QZdlgNccRjWGZMjG47Tc5EdQQ5gvRugtQBLlNLcP8QQC3Uo/m74RFlGNvajPFSaMW7dTGGywWRrtiueTAOOGeSkP1ZnC77WhtV4kEvoBMsNMs0hlTCpJeNBWBBJPp/9LDxWqesRkeS/+HxK3AooUpJhQGuvtvtDqpnNP8LvruqYiU6Vv8PCSVGPHIGokQXp3LE=,iv:eQVIDwqxHPFJsCKL1tK0IzdgLHfdZ5HH/2Yv2Fplbr0=,tag:euuEAPZTKKDa6oJKX6AmuQ==,type:str]
    ACS_SENDER_ADDRESS: ENC[AES256_GCM,data:ouTcivyEVqYGQLaKdNWzvdbmF6Zyl6bWcCs9nWWn,iv:VUjaPrf4kV+1sO1nG/9e6t+aQ2PYrSe19PFLeF+1TRg=,tag:kJLjuAUTJczF23p/EM0HdA==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWREWDRqNVROZTZ1WUYx
            a2VKdUFzalJiQkxJQzlvbEs5THdrbHF2N2lRCmxVL3lKMmcrRDlLb3h4WE9kaGly
            QzVUSEdiMnlXUkhaTHM2Z1FpYmVhOVEKLS0tIFlGU0tZdlk0MWxLK1c0cm1uem1D
            VkordGxGMEtXTGVyd0c3YVJaZjJGR3MKajwDNewoHLcGIqjqUS0GDJDyFA8db4TN
            3ZokZTZQEsqkfj8TL2lNDJVxDYIEezYI+Gxy81EFWweiOtO5hCO9jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T10:11:19Z"
    mac: ENC[AES256_GCM,data:8wPhJgNR5hV8Rf2nmdbNaHdsDTtIUelaBB6fBXX9ujrD85wIwyIFenqE/oSn0Q1RFhb8JWIogTx/mjxC1UbL5tYxfnr9Q6lg+NnK8UShgEAT3z4qQOO3zGnAhFUupx3K6/2xmTD0GxFoK7ZL1slGe14wEGulkZGKShNP8jIKDak=,iv:vdF+iKnuEM54qYs75HHEpD0pCKKcmaEeFjeA3+wZrr0=,tag:r/5ebegjD6LkAIfaNlsEmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
