apiVersion: ENC[AES256_GCM,data:b3A=,iv:oeynKmg0otKXy+Aidk1UZ2VEzvzgWOqPG1DXoVtBqdo=,tag:Vsy2yenHNy9zIFaFxavYjQ==,type:str]
kind: ENC[AES256_GCM,data:JoByJGBg,iv:fAwRi8st+VFTBN3PDb2VITvkZTAYESciiVK9IJDBTJM=,tag:KS1JmiIXAoViJY5mUn0HCg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s6rap/vFl+yXsJRH/z3RE8RTDQM=,iv:yOLbsFQM5M3IVJUSvW0zEVkaOHw2VFp4oY9YoVSm/Vw=,tag:dXEydXSYze6s29FZBD7/xQ==,type:str]
type: ENC[AES256_GCM,data:E/FOfbj5,iv:98uFTKwjHbLaoAdvZHbVHjlOb8KG2Wigu7IpxUg+mds=,tag:yWV6n08H2zmxNn6DawOlTQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:k967AlrPS2I0RQ20wUsva9iw01uaVfaBpENIVQU9ee9jELtaGCZZw9h98y1HjYC+4/U6s2uq8Ieq,iv:2tI7Fw1WvYaAsp0nvJHaMdt80fqtQiZ13aJjA6hhpfk=,tag:RQTkx7zR04ejUH35SkPvuQ==,type:comment]
    #ENC[AES256_GCM,data:OnSgW4YScmOp2j12y7h1fEc+g5xwROhYFrFt6u2FLtVU4HbxxAIdmAj1U0JzXp4=,iv:zl8R/E5YO7+L6k8OAtT6D6W4dkppnqeFHjAVGJEqYa8=,tag:yEz6Zr2Hm/VjIbkuR5cvTg==,type:comment]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:KHHe91Oe/YIHTzNKMF+kpub2VmiLfHESeDfjN+8tcYO6Dw==,iv:DKrUT+lz0pxBwnsQb4RRCXDMqraJyw1LVVjuKqOYpdY=,tag:vfhlfLgPvjWXJogXUnyTAw==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:HVU3HiTg9kbcjd1d65K+Wr8IFE5kGOJXM/koALl1VhI=,iv:psgz/RLMQyzsZ4LHTKh+RzxWRGNjCO8Zg0xDERqyjQ4=,tag:w4YIyBcfwnjQW4/nFnUNZg==,type:str]
    #ENC[AES256_GCM,data:7I9mjiPRIgfe7YpONVHC4mjo2XFscYYFjiW5fpWZaVPOsJYs,iv:oLpQoRUyzuBYMv7F2zOqnxCca1rz4J5C6ck21Ub+seA=,tag:bwDvpbxhe6kGLlPjm8nb9A==,type:comment]
    TWILIO_FROM_NUMBER: ENC[AES256_GCM,data:ql5SvbeRRuCgGd43,iv:RAMaKZV5yF9BohVVe7QT6kxwWQtodk8tj9nZOqD2Ksg=,tag:dze0+JJGrmVsgCgTicJiUw==,type:str]
    #ENC[AES256_GCM,data:5NIvMRUf1hgJWimJPwLYAow8r3qN3tks8q2zTV+FWdqJ1Aw=,iv:rg1np5iPVNts6sgg0wStsW8z9VoRUqMu9KBIm/ZvcxQ=,tag:PYG5ZexYD8gchgqXWcy7qQ==,type:comment]
    TWILIO_TO_NUMBERS: ENC[AES256_GCM,data:LxKs4e14RimBoHFBvD7UjGdOyDinqzu/mVKzyDXT7ElQge3td+uWTxM=,iv:/Li5AbEEHivcDo2wqcqL9Vcp+dIXRxCKfJHvcxrtyXo=,tag:OWZTVAWCyGc+2rmGW5zEkQ==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERWtyU2RsZHZ0T1FFcit5
            TXp0OHhZdUU4V3MzSVE0SHBuWkFWVHNVemxvCjFIZ3FsMjJ0Z0FwamhlajFmQXVD
            aVF5WDl5dnEvT0ZDK3h4MzFLZDR4RWcKLS0tIDNORVlWSlR5VnA3RGtERFlDWDBI
            eXJXU251U0g1T2pLMjJ0WE1wekNmU1UKQ7t+seFQ1Vu15QFl6CaH2RXmogDkrPeR
            BEsyXtMepDOto3rMPPZrkkuSLXL5cal9+WEoqnW5QPqTu9oC5A3KiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T18:56:26Z"
    mac: ENC[AES256_GCM,data:0hgSFtT8JcsWu5HCpATC+l/8y9rAPnYuK9kFMWcCeArqA6TC9rggx/OZg2W/n7tgiJrbHxPS8M9cSGGlbK3Nah/PCeJNqzBcZQvHcbsaCJwMKCiuX80pxI1zrsKIePfiSgJNo3u6ArsS1cX+rEYqdiGQWvZDdNq6IJZ5NfRtRvY=,iv:LPmyzsGWbU5dn5UPG6K0U19nYCN9WGjBTDvrhPYrLbs=,tag:ys1HsLovPzgxrAfaW9cHzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
