apiVersion: ENC[AES256_GCM,data:N6o=,iv:/nAznvWhA8sjQyn+muyye9OfM3cCk+sKtVkUb0dAmvQ=,tag:77dCUY6eZX4c/RvKc9LbWQ==,type:str]
kind: ENC[AES256_GCM,data:lRfgD4+w,iv:huz5HWO6PP2K/V9THZNDacCLG7mk7WWvbyF7DaxNSXE=,tag:+C97RDunMNExWIKbWpyVAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YBftXbsM38ZULDsaJriQW7c=,iv:5aRN77xXm9Wn9VCV+rLaCyOIi9UGa1WLZBdognKi1zw=,tag:wt+vGFhe/TXVWFXg6P/ORQ==,type:str]
type: ENC[AES256_GCM,data:QlmvemDp,iv:VeNMpPvd/DCRdOrxDa3g91oaIRMvOFGsZsr4pBllL7s=,tag:KfgdTQqAVPHRqJ+MFC6New==,type:str]
stringData:
    ACS_CONNECTION_STRING: ENC[AES256_GCM,data:BGdKdGg/9WSV9Q0573+wjs0RLGm1f/lb2WtMMXiWndqvlGWwyUEP5elth+pVk6xm7RjlApuwPnr15uy1UZ2hweYJ8r5+695wAiB18MMtoB3FT8VkUiywo71j8OXGCUyDusKoaQdEmx14/2MKWtl7Nqt3oYP6QDyZrOzMDymuUdQ/GkDoox94TozU04Fz5un1C+JVe7/wvVETSrh7uQrjM6jPXpPKGSL6EsVf5Bo=,iv:kWxpBLezrAhrVgyuZxq/eggOMTvKr/Xa30+2LhEifMA=,tag:AA38RDB1h6TpYYMZQeZuzQ==,type:str]
    ACS_SENDER_ADDRESS: ENC[AES256_GCM,data:d2FjI3mcP8ahWzWdqfm0YqJS/TFWp5HtD5vL9k7Jx8E0uRe07JhUtoPtFgJZWa93EHR+pwUjgZIyGbf+aA==,iv:LooL4Lu1Sv9F1GI9U9M8y6ks0REl4MJXn431sg4cJe4=,tag:d0aWtHddQIR35zOrdNMi/g==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VjQ0Q0t5QnJDekpMaTRa
            bjlKUmNLaGRvYTlaSklacEowS1FQV1IzV1FRCkdQakdxRXRadFhEQXp2NTk5TTBQ
            bVQ3dEtxSVFOOWVJSjVSb2FyZFpjeWsKLS0tIHZ3dUtFSEErYjIxSS9RcnlTbzF1
            d1UwNzdNMm0yaWFaUGtqbG51a0pVRTgKL3XxQh7s+mShVdk5UmvB1Tn21ZESCAEG
            S0YAKGkjkz7bOsbUpVUe90ATHHDp/4dukux6F7heK4zYVObBiKP2dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T20:21:16Z"
    mac: ENC[AES256_GCM,data:YQkaFp+nzSdznsyZ47wl/+H9WF43+20vFKSNGkS7mSTbakWs65xyjn4NenAdssD/BbaTX2q5rU1HIujSuPrUfGtTrRsjZtxV7RaZYUW2uXNtdjvjENYHHK7+fGV0vu7MJp28JvwMZb6KBc5ywnHUO8XVBQR+jU7EbMB380zL5ro=,iv:OaNPCSvvf/5pXMSKukShZG2hC3Dowem38lUbX3qY1Yg=,tag:P9xVvBgVnT6BbftMU1/CYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
