apiVersion: ENC[AES256_GCM,data:JeQ=,iv:vplqtsyX5uc9LDgrA8qBNhRc1VD2jErWD+dLZBCqqUE=,tag:rDv4oMeuiN5LLorIPs0s8A==,type:str]
kind: ENC[AES256_GCM,data:yA6DhMvF,iv:wnopsRfbiFZ0V4JTRidfzK31I32tx7+IwIdXWpvgUTg=,tag:/3qs53+gqxkmHR/YKnMGjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PlydvNb2VkidkWv/JYfM7ZA=,iv:0hWYVNjrXGjtNM9UkzPX3LJRg3VmbsyIHEjrP2MV+Ak=,tag:ZZ6bpuRORLUhvl2+tq5I7g==,type:str]
type: ENC[AES256_GCM,data:hO0LFYfs,iv:umjxpHmR4bx4ETuoryGDppAqwCA/N676A4sSBgh71g0=,tag:EdXAQuK8h59cknpyTZ6iXw==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:WJms4OAhiRsjKXJVSGy4tHmE+9YXCgMWvkkOOF7aMjp4WZmqODRACLPV4IJD5pSBAUkScs/uSBCRHA==,iv:qTtPwpQvbzW6z3TlQHbPrU75aFzFlb3owLKrf0nMnUI=,tag:Lu57LJZ52X7Xyn/yHQunyQ==,type:str]
    SYSTEM_ADMIN_EMAIL: ENC[AES256_GCM,data:q+xLk0uFLZpgM0DOkj7QdbGj,iv:wUDt5xL8F0ipf9ymQKY4Jor5K7JhIL2h+azNs2cQuBU=,tag:bU90penSnLadDC9FbQ2Xaw==,type:str]
    SYSTEM_ADMIN_PASSWORD: ENC[AES256_GCM,data:h21rew8OvctJ9X+45dosdA==,iv:a/nE6DhQjq9Pfu1XPOEPDHZOd2OUuL9EDgEfmMNsUbI=,tag:ox/8PwOQSRjqRmsgcCsBbA==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL3ZGMXNMTnFVdTdXZFpp
            RkllOGZ5cGZ1WGFuTEdDb0o1M1lOMVh4cWxZCk5xeVlmcmh4bnd3QkUwU0FSYm5C
            QktGeldKY0pEdkNKNUtLT1hNd1d5cTAKLS0tIGlLWDBxSVRTS1NaUlF4S1VXR01P
            bEZac2s3ekU3WjRRalNVWnhuOU5WdkEK0yzAI+eZljCVnPpy9dm/FGV0nGXM/Uhx
            eIPt4DgCDr7Q9rw+RtfjrxkVp97jqf5JlpiRXwh+RxA5RLfcKUgEmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:07:30Z"
    mac: ENC[AES256_GCM,data:155mD5NoK0hQgToh/tXawPZpBhEJdmceenduLcXtUXVa77s2XLrap+IQxg3/bFX9PPwSg5qE/+yYUVkKW50WxcZXbQo3q8wWiIMgao8ALfkQlt/8XnwEVhZRrd7qDaNaju/dBZsYvI+ug8dA/cAWz11zE3a7uMBuUKI+zlB4oh4=,iv:rq3frsJJLd270I4L2J2zDwZcEjp5QA1mBlfidKyu4k8=,tag:Tlg70CSY1M1E5KKu9DEW8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
