apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-shell
  labels:
    app: linux-shell
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: linux-shell
  template:
    metadata:
      labels:
        app: linux-shell
    spec:
      containers:
      - name: linux-shell
        image: ubuntu:22.04
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl iputils-ping && tail -f /dev/null"]
        ports:
        - containerPort: 80
