apiVersion: ENC[AES256_GCM,data:dAY=,iv:xGb4RVlEzSpg+6i3iWna7a5FBD7CQQkiPgWvg2FU7gc=,tag:pM4Ll4Gss1Mrscys9Dk7Bg==,type:str]
kind: ENC[AES256_GCM,data:aPKxSOR4,iv:bZny2zNqo0vj9983BGO8kojfrUP7i+ZmQ8Msvv5XrhM=,tag:3lhbhXlHx6j1T5bH+0UX7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UbqlYaOY7OmLjx9snR4H+Ew51gdi6FA=,iv:7V5lMy1JgvRFiU8xLWLAeGL3b4UBJ5UO5wH3KxoEEp0=,tag:PfwJcuoEccZlyI52AXBozg==,type:str]
    namespace: ENC[AES256_GCM,data:6SQdAHRpJQ==,iv:Bl6E7cNoz9UW2DFRHDlmfW6MlsNCAaU1VApcOmNeZvE=,tag:8GVRii8M4uUHPdPHYHqj5Q==,type:str]
stringData:
    postgres-user: ENC[AES256_GCM,data:CHL/lCb6uA==,iv:AOme7q/wKtqgfTNdUCFfglgmzBXdlPZGuWKxxtSnYDI=,tag:dRKdhQcebY/Z1w/WkgH/Kg==,type:str]
    postgres-password: ENC[AES256_GCM,data:2JUMFjnVaw==,iv:BH8+Y8MjAu/UeKYvXJ/lNRAeC+/DjbQTVc8+kiIZ5G8=,tag:xtO1w9HKKV8H8BZEQTmRSw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Zm1lMEMvOVRDU0dwSmc1
            dlJtSlplT3Qxd2U0TFZvbUwzVWZsQ3hnekhFCkZ0a0JISVpxbENMVTBzRk1IKy9o
            enVPTkhuNnZvbEJUdFFEVllTYWtnU0EKLS0tIGVFVGFqelhsS0VjMTNYajM3QWIr
            Y1BORHFDbmY5eWlLT0g3ZkZPQVNrQ2sKC+5lE5zbHxx4ZxKurSZJEVYv6amnpzsR
            IC6LJ9I6kqOSd6fNfFB+phA01In0NuY+a4KvP1KyKxtQLPE6un2VRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T10:34:24Z"
    mac: ENC[AES256_GCM,data:G4U3lVHmDAY/W3h6hpzO6QkhhPFX+iHJh+AGETJOruwxcEmYrerN6H3gVdi64AqU7okuAnsOA/bm2UWEBpufff3ZWC68r2yrhnsWxTmnnrE9YCEvhvS935AamEfc+KeupaiGkuSLeoOOVPxEcWBnsx2oiH+wMAxkgmA3ArbLi/g=,iv:2bp49hs55RwJSCAp1GYA5LYlWjDWxPIDl6oJbSspZRw=,tag:2P7MDcTnG1d4vB2EmL0Jbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
