apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnson-frontend
  labels:
    app: johnson-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: johnson-frontend
  template:
    metadata:
      labels:
        app: johnson-frontend
    spec:
      containers:
      - name: johnson-frontend
        image: prodacr1234.azurecr.io/johnson-frontend:8d95a849defbd116d04976e703068ef48ea3a25d
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5