apiVersion: ENC[AES256_GCM,data:RsY=,iv:eUOEcu/aFU3/Zm/y1R8KN7WjM57jkodMpTc+jUBCpt4=,tag:4Un+IDrLP+lGiIux4PcAbw==,type:str]
kind: ENC[AES256_GCM,data:NriVfcHI,iv:mKDLFPirc4uP9funBM0lEblZbwnbRVr34E0+D09++IU=,tag:aHreFwpday6au0Bfj/ipmA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8uyzCtEYsavfQbDh2RCmXg==,iv:uU8Mu9RTMCOd5lVX1a2FI1T3BsRWFpGVJob+BRZLawQ=,tag:xOZdAaDsp68/zyfP4iQQxw==,type:str]
    namespace: ENC[AES256_GCM,data:mN5XH8phuKE=,iv:gqsducCGeU2O975lVqRZK25NRLj3rYZ2pOzXwRqWHYY=,tag:IwByHKkMkVyB14vURmK1Rw==,type:str]
type: ENC[AES256_GCM,data:+qCwKphN,iv:Ff8ukJ1Vx71Z6xaC5juKaMxpX2TBLwFtbtUu9PPDLwc=,tag:VViaddt1TvZJ3otgQsnWIg==,type:str]
stringData:
    jwt-secret: ENC[AES256_GCM,data:0J780wBBQCdb26ioBVffketw98+vIlJPeEZ4V7DrcgQcueRRr4ap/f9LLj8gQDNULg==,iv:kDFVKx72ILKIjs5VDtSPZKFhLielBuumMpsRouZDkfU=,tag:M3EmxX7ysPuUgkpQeD2mGQ==,type:str]
    azure-storage-account-name: ENC[AES256_GCM,data:G01TA5db0O3Ga4s5toubXQYBeA==,iv:J3xr4ayAS+1swrPum3jS1nfJgsc0DYZ/kUbUaxglbLw=,tag:1WmPL9lXwo7jqUFmU8YN5w==,type:str]
    azure-storage-account-key: ENC[AES256_GCM,data:MkHKMPB1N/+fQf3DQ6CT6EMwZE1gKUyiQ6eWfadd50dYrcqlsMhBdIYx89rJEDy+hOCvMmE7HpgK3WqC4+Um2RiO5L9dps/zlamNJA+npPez6amYyVwkUw==,iv:fGCSbBOb6wm1mUHbvCsHoL+YyYRqExsgFZsVz5L1ii8=,tag:AOWiwj6UiUNpWLG+qnVuZA==,type:str]
    postgres-user: ENC[AES256_GCM,data:Afutjx89HmI=,iv:1pzrmjqLpwxAHqqEuHXLYUFvk8xd2GPuvmC0Y1IteV8=,tag:lTuOUfHcXcRyzjZML+hWtQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:zK3iap1Xvbw=,iv:ABa/gXbsTsRCHZZMXMSqCQUm/Vbj1ZqeQHp+3xmsjLI=,tag:ULSwQ4wH42XDGlW/yT9ATw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOFRkdkhZNXBZbktpWHdq
            N0w1N01kYW5seDJsWldySkxVNmJRYmpoNjNNCjJtNXVUbWY1Nis4eHRUaXRpUFZZ
            NG4xOUMvSVVNcTVPZkUzVXRoWTZxcDgKLS0tIE1iL2N2b0xmRStBQjBEdFl1UlR1
            NjUzdzMrM0NBZzZrODNWQktzQTdPK0kK+6WpNRiK2/1QZQeuFM+UIg1yRgNfyNRJ
            4i24fOc5PgXglwYkU+o7Pne9CIUv4uIoTBVbNdY1ni2519nZH/IJ0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:43:23Z"
    mac: ENC[AES256_GCM,data:7G85qfM18H/etvsElf1Gq1X6vcDoN7WB7fnjs13S6BVXp6p1L8XF5/3UKiIZNhf0RRtGIcLsZyYOYh7wPHnP0wYzVSwY+OWXO/kkaR0+/7FHGo+RXI5wVs4Xg6PWky1XEP8qZRdqu5m+l1OQDn7oDKOqvc7A8qTzz+yHfZzj+rc=,iv:1PTYUb6RPly05K30iJWnyorAcOxbG2pTjG/wBlZIADE=,tag:2U4ACB76oaRoP0pY1VygQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
