apiVersion: ENC[AES256_GCM,data:H9A=,iv:/Ab8lxmv1qI9Mr9u2e0zkegkk1qonCbAaYvE1+Y+Bu4=,tag:XFpLiT6Kx4w9RVh6Fj14qg==,type:str]
kind: ENC[AES256_GCM,data:OM+ofeJb,iv:3DF8rTBRbOk1b4J74FxNRkoszsdYSQXn35uv/++3+IA=,tag:h1iOGipe1vLyVoWl4Ts9OQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p1R0PusF8Gt5VqW6FuLYWC8=,iv:r3LNk/MJTWAsPagXQSg7gJEeJlM8i86zqAPxT9OFcIc=,tag:2uDjImGSkch7XRvzC3NlEw==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:T7JUSBEGyPh+Ic/zYkd666jt3evTGU+MSHtQB+m8f6mJwYu3jRX9ncb/USZXaJn9Wq5+VMM2GpAQq+ftlmbFHOUQPyhZYSCT7kRMNxNYKpIhLIDW+jX6Xs9r2vBBKLZjoBHWN3TDD8UUzBuwR6lKL/gXTfqBuXk/V2Dn,iv:BbVgH0umaLsM07Q0NrP3hxNgqfII2NsHdPl5cAG0wMQ=,tag:BVr6RvYOTyVlrzrozCd+NA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:AZHiEdf90hVD46tcl+SWKRwrQQlMIpSpw9bJyVWEWwctwMd+Mo2oWYu5w3jkjvf1FDPKfT3P9DZKZhec8YdDcw==,iv:2Z+srJdEtPe8vJ3jXkYELZBGtuoHawHhug77GtZMV40=,tag:93ffvQ4gUkSm3UB5eTSlcA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:6onSa9Q25VQvTL0c,iv:ItMgKppim3fDHmKyVYg/b33aSNyDd4NkDjmlBI9+rSE=,tag:btrm5DHT33RrnuYEEsD7sQ==,type:str]
    TWILIO_ACCOUNT_SID: ""
    TWILIO_AUTH_TOKEN: ""
    GROW_USER_ID: ""
    GROW_PAGE_CODE: ""
    GROW_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRDBLNDZ3YjFHRkd2N0NK
            UFphYXhPN29jQ2dNN01tdjg3UXptUTN3Vlg4CmlybkNLajd6a0JJODVObXYzT3Na
            RWFVSkJKSC83R25sbUNFN0J0NjExWncKLS0tIG5ldjM2dW8wRmVmb3J2QXBDQ0Fm
            Mm4zeWZLYjZlUGR5b1QrZHFiZWo2THMKjjGmfBdnp0YwJRJAzbG7MgUSmCSlGywB
            eZQtYY34Omasu/GGhbgljtMKV9At56p5Ss14uGj/x8G9P0BFpHJg8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-06-06T11:12:24Z"
    mac: ENC[AES256_GCM,data:ABY+mZSt9AuVaRRComvmKtePaYbHEp+LWltWKW6nuTLdc80V39oztOCiHcwpcprx5oVN8PnTAMRmzXVf9geQ11NFpznZmR80jDJ2jIb0bg/FL+F0V4BmD/hbxKlxcjDHZQOSwHPk9RgSlRu/cQbdy/b2pqzgIt0Tubk49ZYMI+U=,iv:BoRIP7C9LLZ8YUu+vQXOCNgqxPmYBEb5yoGVsiOGbOY=,tag:+JnxFlqrtHYsBomhpF54dg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
