apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-demo-be
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: clusters/development/argo-rollouts-demo-be
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts-demo-be
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 