apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blutag-pointer-push-data
  labels:
    app: blutag-pointer-push
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
