apiVersion: ENC[AES256_GCM,data:nmM=,iv:0sP7kjlfk+YRgYSrOypjtl7m9Pk0k13fYm7vS+aCDrs=,tag:MmuA/D9prIn7lGxh/I81xA==,type:str]
kind: ENC[AES256_GCM,data:boZBQz4C,iv:RdGBKhnkpWKJwQsgGQzHuVgCZxSyllxOiejqMk0SFt8=,tag:gSUtr517bRnFcrLaBaY2qQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4QFvEZNKzSp0sohDq8Zw/17WOyDTVK2LTs8=,iv:tFYR5NbZHjAaZY+b88/9xzN/+eBDMXFEvnbQoT0NDTA=,tag:sRy9wdX6R0eFiAMzKnXH2g==,type:str]
type: ENC[AES256_GCM,data:n41B6Yts,iv:K75rOD+9XGm+ygzjafI0v6OX+QlCnKE2UEy/PALGQnY=,tag:mZ0RglDV3rc2R0Lz47TfEA==,type:str]
stringData:
    POINTER_USERNAME: ENC[AES256_GCM,data:G5vdTf1Zf419XQ==,iv:nSwyy08vkhgtEBrLN6ine+uaPQUZXlc39g/zIK17nQc=,tag:qp0d0ir2aUGJQglcJFqbaA==,type:str]
    POINTER_PASSWORD: ENC[AES256_GCM,data:24wkxf5m2a6dyurKOjAjySOi6nb9xs8KHOkx4IOcX/9NFx6s,iv:YC44nDgefkTwDT8Cd2RlSuHLXithvkZUiONALufJVt4=,tag:GarTT9ZhfH9HHez6eequ4g==,type:str]
    POINTER_ACCOUNT_ID: ENC[AES256_GCM,data:WZTy/Q==,iv:nJfIyyNfysAM1g+uO9zMrR0ApXt00v65XRdJYPSJUfA=,tag:kowAoxsURlzh8+HvaJYa6A==,type:str]
    #ENC[AES256_GCM,data:OTgNlys4enRklbr31YfGwOkV9tjRnmc4RWfPUKp7XKfGZJ2lgxiWrV3wl6RJBpWlYqbWH/XrDqaxVIoRGQ2VGeYGRHoDLzUe7P6ZSUKlGYFnRhc=,iv:Y7AqAirLequhJKoMa4doxkmOXfp1Mcyh0BdNjZnrVPc=,tag:i2F8Ktc+uAxUKCiTjV/IrA==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:ZPTVMNM3HoCkfc3E0QTDUGqghHCc65YX63gsvCE2HuNIPeWf7QRdTtX3yaXjVhXwIYwvWThI0M+WC47v36lbOQ==,iv:EcyK8U5U0mweDoBMLSWkDrbhCC3n7StwwtGp4cz4TH8=,tag:eBCps4omxEPBTIdmbjJJAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYkplRHBPOEZWd3VvL1Qr
            YW9mTXBCNndPSC9yaXMrU2tkUVFuVnBKaG1FCnYzRVpJbGlMS2VsN3YxVlFOb2RR
            VnZwVUYraHFTR2JOaHFoclNrdTd0NzgKLS0tIEpXb1BENDdHWVpVY3FUcmhJVGZS
            d3dqL28yZ0trZnhURHlOT2swd1BxZ1kKTeQjrqq7oWKYGcZuhdm8InRyDr1TDLM4
            IIn8od++ZUzexlXOZqrCBlDsTCzC6WjQ3C8lKyksLzHpDDWscsWYOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-06-03T05:02:26Z"
    mac: ENC[AES256_GCM,data:AaOSz+/BDRaOJL7GO1I17zNIdwKQRSY+JSQgAgbmNsLWrqT7RI7l25vRpFjgr/vJ7jS8hTwPjmAPTbt/CU1YwJTuSDlD2nWzfMhn3BU66kxv8mgO7PjAUrNEPcL8GEwkRpyAs7CopVQsB3u7ntnwVhm1ttOEWhWhtbbsY+b+zus=,iv:D6LIm98pQnDxgmTR7La8NxqWU81YlVU96t7+UYSXAlo=,tag:Tl71mQ3ye0na+Q2ZQ8QsLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
