apiVersion: ENC[AES256_GCM,data:X+g=,iv:u3Cnu6Dnn758sr6OEFwjvUJuqNX6881cMeNvEDfWYxE=,tag:cDoSBpoBHPHhVude+hVIGg==,type:str]
kind: ENC[AES256_GCM,data:0IwNethl,iv:bM0sYxP7pmKuGeENR1U+G0Pvok7CkaITjEsOioiHrtM=,tag:qiTM5h4KUoRvQaC5tu3HbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nJDacFZ+7zjqux5jnbONh9rjM8sK0kJ+i54=,iv:+4V1+rPsseymiFRqhFiZITogACZyBaqh0/wHcwat8i4=,tag:Ug/UX/axtI5zVXKaqkmTOA==,type:str]
type: ENC[AES256_GCM,data:uRqOMS/3,iv:tmh2EAdiVnOQphERmW2zy+wbnnSylSBdT0OAMSe6WQg=,tag:ob+2E24cz3/vB++wrpempw==,type:str]
stringData:
    POINTER_USERNAME: ENC[AES256_GCM,data:/bYKkstBe5bx,iv:Bqfu8+oXsDzKoZutwdkGasKvQMjrlMuPPxlSXyxaHkg=,tag:6sDrPzH1lcIlYatV/i3suA==,type:str]
    POINTER_PASSWORD: ENC[AES256_GCM,data:hkjSL/lVd6NKjlf+aqud1GfonToixscNVp6o4sbFudIS01y1,iv:Z2jJROgJy6v+t9mvzGEfWveRdlz2sELDYvFXjPsD8+I=,tag:ErCgYkTO22WkCN/JYqOdeA==,type:str]
    POINTER_ACCOUNT_ID: ENC[AES256_GCM,data:/fJm/A==,iv:f6tgoSl8RNPCCdNSyJ7wi/SHMgj0U3Y7Eeh9Pa/E+5U=,tag:Rn5SothsDneKceulzw6rUw==,type:str]
    #ENC[AES256_GCM,data:VLfDPji7efp0crDq0PO9HwfIGKjm8T8Llw0zReQNxdNF6l0LeKandUZp5DlroFL7h5oWXc11CbdOwImkDZB2XkDf8r4eqwVxaO3M4YNgwFid7Ss=,iv:QRWUIIbbHNZkbZy6uYbtXOgypb5+IAg/gq0H3EGAY7o=,tag:eO/WaEy9MSuuTWVz4gpnAA==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:bidEe0pT6/Ci65pL5fpF8pcLqOiN8fH9U/yO/Q6IW9Zw6Y+BqMOYtxZbt3cKKaLlvPu3sQVyFd3liaVfYU5CvQ==,iv:OCThA0sGvu/1vHSmlHljMviKNdKV2DRse0DALdRJp68=,tag:uzVGIjIBgtyyxsLQx+gT5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZGV5cUdSTi9rbnpGdzBB
            UVR0YStXOUE1a21qTGRXL05VbWNJZnp4RTBRCjdGVXJnVnlRZ3FUSFV1YjlDVC8v
            V1ZnRU5HQ2lZY2EwKzhhYzNOQ2wzaUUKLS0tIGh3MzRLVlB0b0E4R0VTcVhMVWtV
            Y0xDTitMaFArZm1hMXZyRmlHSWpZNGcKkQJ1AnB8kvG2btiDa6tRBwPOJkGNXgVC
            D9RisIXIFvcGL6ogADWA0aoWpeEKNxr+GmIqIbHxliqG8C0xFxwdkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-06-02T12:40:14Z"
    mac: ENC[AES256_GCM,data:YoeZ33MVmgft3scSgFNNSF+kETfCEkt9Yz62lSQACySxqHbZYo89/U8/CMGwkrYPeV4zdM1Q62tZiWfivOLPUVtc5aC873Sq8AC4ayAiaoLVfUg81wCmAoyiVf7gO4AzDDEDDwNIImpvL61hSaCrulN/22HfMHyxzV9Nb+rzU40=,iv:OPhnjYt/8wbc+STSUHBYrAk88xn4/VXGySgzRbOdVNk=,tag:qSTvmsFpZfr11212x5KTUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
