apiVersion: v1
kind: Service
metadata:
  name: blutag-pointer-push
  labels:
    app: blutag-pointer-push
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: blutag-pointer-push
