apiVersion: ENC[AES256_GCM,data:Mfg=,iv:qGGBi8qr4cke9jElQDOmjuyn77aZ+CroWN1BDgekRXY=,tag:ppibCMMoM9HfeR00RkZ44A==,type:str]
data:
    postgres-password: ENC[AES256_GCM,data:ohefnmoTnvSET4b0c2E8uB8J58y7cYI6/+mYXVGlqO4j6o2vv0z5zP53mg8DASyODIEJMMHgRYtyyvisYzZxRSk4mN0dn6wxla+XaZTzp6dgk/oKMMHopQ==,iv:98yhTTOh3nUr0AWV2OfH6L0pcAvVNDuhix/YxoY2HTU=,tag:CDSf4cQgGJ0691TW6BfdEQ==,type:str]
    postgres-user: ENC[AES256_GCM,data:WOmDd6PtuGA=,iv:W2FxmF4vTYdJJ+CIh/0GH5UIHtW2VO11rS0LSG6gvqw=,tag:BCcqeJThCe7ZD5cOW7EZ8A==,type:str]
kind: ENC[AES256_GCM,data:gw9+fKci,iv:syUgvxdtf8+egrP2Bf1jAz6K5W8fywJW2O9H25uA7H4=,tag:AoDWeVco0933gDqx0yvF4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h4zVs659RTyvHhrK9ekoafQPhFg=,iv:UzOJ8iwmsVjP2wtDq+lLELbY+rXzEHTpS8qAnw8dQMc=,tag:VBDj6DXsJm63QRW2Yqs9ZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y1NSMVVDekhxbEV5OVQ3
            bERvVEplVG5yNkQ1RUhzRitnRXZrR0VLRjE0ClJxUlI1UzgrZXpPQk1VT0lxcEV0
            RmtEcTdjR0JoZWw5cTFNVFlZajhpaWMKLS0tIEVPOURCL2ltY08xUGN3amNjZURw
            ZWpxMm5CUTNxK1JwcStFQUpOOTR3bFkKLCQAdVzqdNpEO5NE8U3h/4fvsv25zFs9
            VyG70dLXlPhKHRZ52Qw+2odHvyDVBhY2xl2wJY5aqy4z7gLsan80jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-08-29T15:35:18Z"
    mac: ENC[AES256_GCM,data:k+EYXEdLQD2r1gSkRVS5lvlnBoeTSXWmqVYjwIz951TjZmRhg+7G3iCzQk9oEXnd5n9xGIRnmipaqwuP2sPFJhXm9ArheUrGJAnp3rJnG3cBWFFbP5MdLMOMdU9Z0OSEmw2ZTPXEDD2k8jiOyn7zWBMPOc8NVoGwzPgG9t9mKAg=,iv:59Su0uzlrQr2mLrsMfipzkz7mCncFTQWZJgwe14tZ94=,tag:FRYyyzDphcwJbwSvB6yR6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
