apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blutag-findmy-data
  labels:
    app: blutag-findmy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
