apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob-ids.yaml
  - cronjob-dirtbike.yaml
  - cronjob-hasadnaa.yaml
  - cronjob-genrag.yaml
  - cronjob-blutag.yaml

generators:
  - secrets-generator.yaml
