apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  # Note: secrets.yaml is not included by default to avoid committing secrets to git
  # Create the secret manually using the instructions in secrets.yaml

