apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - shadow-corpus-benchmark-v17.yaml
  - service.yaml
  - ingress.yaml

generators:
  - secrets-generator.yaml
