apiVersion: ENC[AES256_GCM,data:iz4=,iv:iVqlvYVRa/V2JT3hL/LanBwKiGTVw6cMbfBWdQY/Ml8=,tag:MHLisvTGSoXvYONDkI0Cyw==,type:str]
kind: ENC[AES256_GCM,data:2fMDw+lE,iv:FgUGr6Cf11FC5rcSxrIXCiEPzgPPckD1/anAOndYnfw=,tag:ixd9K+g8LcTKa42DLWyD3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kkQCjzBhVRcbASN9oY9wQJYN5sA=,iv:62KAaKECHV+ptnwPfYSdQlpOdX9vctgjKvHgxcpdKyo=,tag:lmznZazgD5M3m/yow1Qv1g==,type:str]
    namespace: ENC[AES256_GCM,data:OM1A+Omt4d8=,iv:p8frhJBkcwE3xgNVtCoZC+l/CiU2rKeLtUy2j/sgdM0=,tag:+6LZ8I6aWyewSoE/F+kkaA==,type:str]
type: ENC[AES256_GCM,data:m+DaDQD/,iv:jpKv9dDyQH+0+EFtvAu0EJ1vZgZEyvtJWTYFJHbARt8=,tag:bNyaIY7gW1aBJ8lfwJ7yDg==,type:str]
stringData:
    AZURE_OPENAI_ENDPOINT: ENC[AES256_GCM,data:hMflEsIGWdgF2ujXssC6KGFsGYxjCXPb2ECyzfJucwTkSg+1zJuhkzNV,iv:LHjBwZHKqrprVWji4B5OzfUmWaMCEh6t53tTm39xQJg=,tag:UR5GySvIyOahN4ULvcBcOw==,type:str]
    AZURE_OPENAI_API_KEY: ENC[AES256_GCM,data:seAWzDjSixvNSTfVn/1Y8bCGaW4o4UjmCvxvQpMaYVD4wPOGM6/h3Js/+rLA7kkAvuESuGTkaG+r31YW13l5JmohxK4CSgzl94ElLfOrrH+72UgR,iv:82zMlBfSS73/hXk6tCzLeEuX79qVTqZAIeGY9pwVYi8=,tag:4oDAH+KoMssfOxF9lUKGpg==,type:str]
    AZURE_OPENAI_DEPLOYMENT_NAME: ENC[AES256_GCM,data:IS3cimVy,iv:+L4fb0tTe4to1GqmtzqdXRzvK+8yS03DcnK7J7fieiU=,tag:uzy88S1T5bksuAsWpjgUqg==,type:str]
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:7l3F9Pc17mVRy/6F,iv:qSSgG+ALFbU2JdWcrIGegQLt0I54icK/rQc57jI3oU0=,tag:0idaFCrIXZjrJ0TVzJZ25g==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:CQNoZavcBzC5inW7IzcTrBfj2h8OcqAmSPByYvMq7yxx5XSgaOg3,iv:YwEae/uAA7z4WtfIWfm7jZKDcuv5ZIZDH6zHNZMs1HM=,tag:4TNPIBgYNKMh9AGRXtehvw==,type:str]
    AUTH_SESSION_SECRET: ENC[AES256_GCM,data:PEkqxnWYfBAtMBPbeHuuvP9WIAzhlv0CdM+LOrVmkKXXiv0mKM8ALnpabIE=,iv:r+PyjvobncPDNYDYMc49QCdZOcD006wk4j6Y7JFMnhM=,tag:8Ld2yCC+x/ygXJzZj/fZ4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd3Evd2tqc3U0ZGxUVGFX
            anFDVXhrUUVNSnI0ZEVjQXhWMU1lMGsvMWk4CjlhZkRqTERkMkJLVU1ITTlOdjdK
            eTVzYXRXL3p4eHZQNXY2azBRRllKemsKLS0tIG9OVmQ2TXBmd2VESzNFWFlHZ0p3
            Y3g0SVk0Vk83RWJ3QVhjVUVQY05XT2sK09eU8SFsa588frGQ7lb/GV9ZJVzaEY46
            KUHnHcDjiGTrPwEtFlAeSDTof7CoJGQRXUPpnEIq75dkm/H20j/M7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-08-10T15:48:15Z"
    mac: ENC[AES256_GCM,data:vnyTH9/CzDS69mHbo+NwqzCiNW8tuDehxUG1Ovwad0uWh0shxjuU6gGeoF9oRFYVQetW7+hynNHK96MHa9K1seUBeQ0tYH/Cwmw+qSnXA3s9kMM3pTgBe3F6NLAPqZuyU9Ay6daLsx7J5z92GWUxHfgKg0DUeD3bjv94lRdqMMw=,iv:GPxr5yxh90Dq357zcGhlRDy5BNC6tX2c1s63DMiCJy4=,tag:gzZYpAlyXeAAfsF8O6junw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
