apiVersion: ENC[AES256_GCM,data:2g4=,iv:cf0mrSkvS/QN2EZEQIyNdq3jA7uTPvXBwVYe3U6L9V0=,tag:zvTCeCz3aQiv2eaF3XVtiQ==,type:str]
kind: ENC[AES256_GCM,data:IeZdyWW3,iv:prMC2w8+9NiFVVQJRk4GsBn4XUSLMV6oF51Vg1kv424=,tag:kPIdLNhfCTMl6cq/jD/DaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5tyATlahv3BNnCiJ5sFQlTOkTcU=,iv:22LDp0cy3yq4TfTaqxrhiRZHmXwJqJTVsB9ObAnsO5g=,tag:axhK7AeCu36paaFj1AX80w==,type:str]
    namespace: ENC[AES256_GCM,data:gQcvWZYLLzM=,iv:/a9liTSrWi0SoR5tkoVjdYtzt0qpNGBK8wVbMl1y4Q4=,tag:sR8aSZ4N8ZWbD2ebAkDZpg==,type:str]
type: ENC[AES256_GCM,data:mPaBgKWP,iv:HUXf9jVIYSPOEprNRcS/TKwJg5yzEdOgm5VBhB9XuKw=,tag:bNy3HTgSeESQzJxGna3t4A==,type:str]
stringData:
    AZURE_OPENAI_ENDPOINT: ENC[AES256_GCM,data:NnvOtLpJ/vdy3VvLa4MvGfvGxLqtLmhlNU0+qcw6syvBJ2aqDE2r59Nu,iv:Prbi1M675F+MILVmXkRF8UPMVwkT0SQ4ZLfyfKgOa7Q=,tag:GzsDg2JdZ+G84gBhBJi0TQ==,type:str]
    AZURE_OPENAI_API_KEY: ENC[AES256_GCM,data:rPdfLpYd7l4eBbG/j4K18SoTUzSvYm+Tty6S4OWTY86qka6RZ3Bm0r0rG2z7z6e9KZu16qd9y/tV9joYhUlCf1qM8lz5d6eveb7To0iE43jJYzw8,iv:MWEIA2dpP+lWZMwcaiCRAU3q1FkQvX4Nd0kjNePj+6Y=,tag:CaoaiTIxgCdZjd2PgPIaBA==,type:str]
    AZURE_OPENAI_DEPLOYMENT_NAME: ENC[AES256_GCM,data:yfWkNUxP,iv:+IiHYbsKk4xW9gI1ACLpISEuT7gzfcVmknRJ4sLk5C0=,tag:VGyCv5p5CkqSmEWDmFb2Yw==,type:str]
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:E7pVkjbwbN+iIMMO,iv:R34vGKv2VLgTSLwWhOM1Y8MDR5U8Yj2SIP2NKA+8kTM=,tag:jaxKZ6qGoZGpUVqW5PwVtA==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:fDWZ3abEt7gX3zYUJ90FEDzORaxpTjw80msVTFN0eXp4IKllVkfR,iv:nRTv8i93rOWrQMMvMHo1E5fXU/VJS5wgigK/2DzCsns=,tag:qwpOCYM0Qx3Vt/wlcrgaCw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeXAxRUZ2VytXQ2dEM21K
            T2xXeXUyTkwzK1ZCRy9mTFJia0lIcXN1cmhBClloR0QrTW9ybHRzSlhGejdLTDV3
            N2ovV01aczU1YUd2Z09UMm9qN0lDdm8KLS0tIC9yelJZWEZYRnpMNlJidXdUUGEx
            am9pNVdkUDdqVi90dHBseGpFRW1QSDgK+mBe+BLwB7lRK5aYaPkpKb1tRI4Jr3LF
            TwwwDXJDcpzUSx1cc8g0Cm7VAllojWImBHsN/SHkgt/yCdmxLIf8qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T13:45:56Z"
    mac: ENC[AES256_GCM,data:reEbdT6Hb+uiSKBTIxsvf9qrRNVq8VZ2pD1P7+ulL+Y+L2/D3JwEOUMY5120fK8OP9puBawmcVvKjBfNXQmqa5h7eD/BvmTKkxmMxmXUOFej4Ovre/cIP88525R02tu+0fCgBb4BYNMmQ3V9oqQ4yBmVcKpCVKDBIqDDdbAYnJk=,iv:hxR9sOS4tU/oDAnfS+ROvNeV1BMWLNU9soY5c0kgxwU=,tag:qodh5eJiL6VMCfCgdumq8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
