apiVersion: ENC[AES256_GCM,data:yUc=,iv:+4oZ+i05/vcljsZLf4MGdBZnS87z7Yzb7UfCq3DCew8=,tag:1avyaJTWm5ICzL2xY4XtOw==,type:str]
kind: ENC[AES256_GCM,data:5rm2c0q7,iv:QShc+rPjzXIRVDj6ZDkVcTA+ZWbH1mb5NhxwOf5wy1w=,tag:f++zh+x7/YyQ9SAJXD8FNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Jz0Sc8Dtb0K0SMSaViJwuq912uY+d2aTppSeX/IFf86yGQ==,iv:LtWYt6TNF/ByTVHK3cOHQ4mpOP69nejvZ9kenVwaPa8=,tag:jj0d00cTyg9nz8edKTNk5w==,type:str]
    namespace: ENC[AES256_GCM,data:a43LNV1PMsk=,iv:8NUHalTN6ZMlMnWQ5wnZ8hiA/AtK3TNfVsbDc7EjieE=,tag:EXtak5ARMSiE9o8Krwq57g==,type:str]
type: ENC[AES256_GCM,data:a9zA1g+e,iv:RN+DpNbd0Wv6UUnsa1IyEDOZYROOJ1XdRJCLe4ANjK4=,tag:15QlABcTlbgSXFkXi2TDxQ==,type:str]
stringData:
    AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT: ENC[AES256_GCM,data:ki+V/z6kqumYouw7d3dSHRv22KzaH0OKUmpajbyYSQ8kFp46nsS0fgPr/OaOy2zAA/LBTrVI/g==,iv:RATbMiE28BGNcyLHMAhKl9bAz7JVZXNSYVHpNZhCg3k=,tag:MPAKRC1lh8QQFQxeUP6B8Q==,type:str]
    AZURE_DOCUMENT_INTELLIGENCE_KEY: ENC[AES256_GCM,data:RQD4a+/pZN9wqtQuQvx5z9jUXr5WeKcglnfYJa380wQ/icO9YwfBDHv4n9z4DcHX4G4MHOSYxz0ilvCr/VwI5HKXJcU38BEv6zwOZRbW+9cqF0BQ,iv:W18I6+F78a7wgYhVlmt3l/IZaMzjevNFCutS4pQAcOA=,tag:x3lZjYpDu8qiFYxkiJMajA==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbCtST1NMNEQ5TGpIUkhr
            TE5MTFpLekg3RVNRbUNneFE2RTFkWnBEeUFFCmZTR2NTMDYzall2SXZqU29GOURP
            cmhzZGtNNGdKVUhkUEdBNGgyZEh0TVkKLS0tIFNTMlRnODhZNmY2R1FBUHZSYVJo
            clY0UHh5dldHb3ZteUlXTVg4QzBPZ2sKIMbbghreWovpT6pA+bF7Try8d7chaGpX
            n4GPQR0ytufxLN3D9prMtoFjXc7XX5vQxwrJSwtoaToNeWEbweeq9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T10:37:08Z"
    mac: ENC[AES256_GCM,data:8bnSfNt2HWIdmElDOgFhiewBqBDAOM4/jYddAvEEDNNMMHMcrzex28uSVJOdvYe6B9HI4fUVQiEt5XiM179UpwIbMim9qba2hO9tqgytbWlNV9a+IycTnz+vIeetu1TZeIb8+0nKdY7zDHXFZhBtP29MuBw+PJx9273glbJuapw=,iv:n9d1SuzPBSqBP40QtYJs0CLwmpf2TmB4I3n/w2d+wDs=,tag:QX+isbkdcJqHGOZIctG2iQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
