apiVersion: ENC[AES256_GCM,data:6Wg=,iv:h60fYrCAkmI6PLYzZFWZnVy+zsNqH/I63zYzpqGYwpU=,tag:SDubAhhA1ssL6OrWkzD4PA==,type:str]
kind: ENC[AES256_GCM,data:QM/qXX+/,iv:1Z68KsxppA6IXIc0HyfdcffwebGxiOUYzfgvKnSci9c=,tag:d0coWRCi2v83YwHoy6+vwg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lcMN3D9Ku673OXDZ5MVHbJEe1T0=,iv:4mfIk0W9uarYGFiSY0ONu06wLzmRt6kjwG3mMXB1dzc=,tag:JKEYI2OvDiDfJUxmqoBDyw==,type:str]
    namespace: ENC[AES256_GCM,data:KZHe8ahuidM=,iv:1YkAPLVYWjmq1QRAQE5kdn2vygWAjZmNWTIDIyLbRek=,tag:oowNSxBfHfm2lpl3HFeqJg==,type:str]
type: ENC[AES256_GCM,data:MvQ1wCXK,iv:NDIQwkK0lXE33xDt4ZeDm5tlBaY5BxbVpp7v4FDD3p8=,tag:yhxEh+3DcuJ7uIcqZ9qA9g==,type:str]
stringData:
    AZURE_OPENAI_ENDPOINT: ENC[AES256_GCM,data:XJdPa72Wuu5v8Z9gNxSG2wFnOsaBgSi8UL16ygyzoM7LBfUOtf0QAGCp,iv:qs7mBkGmKagCIXr/66nAlJFR+OQnVhgjoCMY9vwEhB4=,tag:+1gp6qYWKKUtzeGjRR090g==,type:str]
    AZURE_OPENAI_API_KEY: ENC[AES256_GCM,data:c285Fr63OqKPKSrfoBh9viuIb1XANawzHdCVPxpDP22+aM0q9EG2RmgHwJEebjF6I48JelOtinX2EdDNfBfslWFdoZGC3nAwFlJKa6hlRr7u9Lyg,iv:Z5iqatbiWZIo5F44aOMbFVGeDPh3qTG6RHwpV1szmac=,tag:AQWFgfRLWVvk5WlgGI0MyQ==,type:str]
    AZURE_OPENAI_DEPLOYMENT_NAME: ENC[AES256_GCM,data:oaXn6JXB,iv:hF+H1vZ1uMuGZk+OtqwREr4fVO9Y5st0DDEmlEwVKIM=,tag:GS7Q/56ySDoFop4FbojUug==,type:str]
    BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:ogxUBBcie22YCpeU,iv:AH/B1I5igGM7fME/YYKm8MUngtNRcH99oLlv4GMTnrg=,tag:U+a6tmxCZ1ffjiVYfkXCGg==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:sLYS9t6kysGdEakVliQnwfuiQAO0hnudrg20LXxv0uyhEyMfC1EV,iv:W9u4KasLnGc9AskGbcgC2Io7Z/fzZSzoaQx6i88opp8=,tag:caTtMmoS8+N+ZlDhO+02zA==,type:str]
    AUTH_SESSION_SECRET: ENC[AES256_GCM,data:R5P7Vd1y2TuC5yfpi8cDo2C7tmsPV3rwungX8NDC6qmIbAOQjNK8XoKVjnU=,iv:ZUPKLZNEgrstwDkBxk4XiUz1irflpCSEWaFqv2Ce8jQ=,tag:sbIFWRMLR4PMpOU8ZtXRCA==,type:str]
    OWNER_EMAILS: ENC[AES256_GCM,data:DaUnc0lvkez2YeCFhBz9XuFRhzs=,iv:PaCSU46SKjoPUJ1Ew1s9oX6sQv87dJWeRiVp85arhPI=,tag:7KIza3+KWtLWBydyrWPpSg==,type:str]
    OWNER_PHONES: ENC[AES256_GCM,data:cbtpyZ2bfE34fY9axA==,iv:CcBDkBD/503uhcOJWt7fbKwEyeT52GIb/VL1MV8U8yY=,tag:l9GVa7N/V7Q4BDNjpkWGTg==,type:str]
    TWILIO_ACCOUNT_SID: ENC[AES256_GCM,data:EdI+OG0hnPzxWjGJ9G3c0OB6BiFsilsEhXZ0Iuoy5P5+ww==,iv:qmqTNgXhrfwp6hkEqtcWcdEJWBUBTD56i+wMkGB0V70=,tag:g/8dsH2XpAT1V6l+SO0uxg==,type:str]
    TWILIO_AUTH_TOKEN: ENC[AES256_GCM,data:y2XscIdgvHjTokDnPo220yTiPJxojpSBGIaOnQh0mhY=,iv:rCfTg+npjYgEywNyTz+TLRiPqtW7Eul4sFWZLmSRS4s=,tag:Qy++togYtDS06daxpSb2zg==,type:str]
    TWILIO_SMS_FROM: ENC[AES256_GCM,data:Fjb1,iv:0xb9jgZWaOtULPBaxyP5THxVjfSCUv6TqGyz+ijoNFM=,tag:NP94yOpjqzUl241XhmQDUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WGp3Qm5pNmZNRXdQbllq
            S1RMaFBQWEtDcDJTRGc5SWc2NEdCZGE1aGcwCnlMVDR1WUNKOCs1TFJ1MlM2MVhT
            alVwUFMvdVJ6ZXNpZEVGUGtFSDdobjgKLS0tIEJOKzk3YVpvbG1rUXJpU0F1KzhK
            amFQdDNha0xnQk1INVhmanlaOW9tSHMKiDaNixZa1mBF1GuE/2m2YGnPIAVO5kP5
            G5vN5f9ZmsdAQzq7wqeGVsi4/OU7YdRMiYp9ZObcxXxde+zS2ZjhLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-08-10T19:16:04Z"
    mac: ENC[AES256_GCM,data:O0Ih0msNiTUA4Nc34veCoGBwaWLj4Sy3nbWdjZHNRlBqi3agK35o39mbSWnu37prJPQHoTm/AxmhdJB5SMNshKgWGNjh38ty9565eLUp/MHn6i5CrqbYZyrfDz+M3aGk9hjINPU7oLDGU5n8eWXytC/l6/18wMkHbVdXofZt250=,iv:3Iq2Pafmbfc6H6uRCIOZCPDJs5ktxxmf7zEMZT+O0S8=,tag:JRAcYx6Sir21TsM/s0yOFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
