apiVersion: ENC[AES256_GCM,data:yOA=,iv:D42lwL5jecUD2o2BA+WOGHQD6V0dETRcATzbUYTBII4=,tag:Tkv+DbStYMFglYRvm86ohA==,type:str]
kind: ENC[AES256_GCM,data:CvJyoKwH,iv:Kg6gg+TJ5lUEk026bY4yYAOKYtUaPRdgxyaubR4TYgQ=,tag:d17c+G41RY0TqaQFBq6r8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nZdwj5f8un/taWNsCxm8IhEtOw==,iv:JslF4vU1LkMOzCIA6Faj3w7TneTljC8w3eC6anGCkSY=,tag:dY708CmOW6o9sf03a/8s+w==,type:str]
    namespace: ENC[AES256_GCM,data:ibx+q8O773o=,iv:AzLH8xu7YI05n6Xzz90yTAxiJQJixik7P3SndjV+9io=,tag:+kiBv8BF4TIaC8YJS93sPQ==,type:str]
type: ENC[AES256_GCM,data:437CEj8i,iv:IehTJkysVKljyOa3EtMxhLJSIV0ESE7PgIvdPWvuEPI=,tag:YIYuvXhEPGWgROIVPXZZoQ==,type:str]
stringData:
    AZURE_SPEECH_KEY: ENC[AES256_GCM,data:qvzwTC8hmQ0bfY2qO4jqGE6GAereZHvtcExU+OKrv8KHsH+pwYl7AYAo8jqdC8gX1opnzuHG6P/wTIfohGEjgyYcz3sJJah9woyg9r5ZF6iIX0HI,iv:5WeZqMnlW0E78sRy7CfsARPRm+O+T8YM+MPWeBapwrQ=,tag:nevnXS2sRx0euyzEcM2ACA==,type:str]
    AZURE_SPEECH_REGION: ENC[AES256_GCM,data:ehHneUfl,iv:I5VXoBpi67NKmAg6JXUKhZsmFzlPHpjDk7GUr/aDmXE=,tag:abnAEeHt64nvn7822pQEng==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eWVRcnZLUFA2VlUxUzlh
            RVBQWWJBOVVDSW1oQnhHSWZaRjBnUHd1d3pjCnRvL3owOTViWUJJME1WY0pnNHJF
            ZHU0TVVvdU5ON3Z6SWx6WEIzNThTdFEKLS0tIEljYWpyNnJ1TjlNQUx2U0dOOWIx
            Sm1SQzZWRzRDT25oS0F2VnV0RUVyV28KdQXAHKgmvQgRVoY2dUXkvhadRP4dZJ99
            t8lqPoaICc8b2Xlqzy4e7C9F3cutwurCJIbwYK3Eg7ZByHQ8eQIS0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T07:44:06Z"
    mac: ENC[AES256_GCM,data:Sj8RzoYoaHm5CRqDoZnfdeBa7Q1TqqXap8BHOlbikU+BpDHQJfNToRBhSNy4PtTaETo5H0TnnJoSUB/HKzjhtvx5tRRFyTLfWY+ikFEoW924jPHFQksV5AlF0EAdN2+Ww395bvGR5UzIoPsWsCQGpgMUjMi60dwV24ayljnq6I0=,iv:0TSnsG1hzdYljpl0F0WjC1Gl98M7tV1en+a/50ExvGE=,tag:bVDtWKHUoyLI6gKPX/NCdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
