apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-notifications
  annotations:
    external-dns.alpha.kubernetes.io/hostname: slack-notifications.jshipster.io
spec:
  ingressClassName: nginx
  rules:
  - host: slack-notifications.jshipster.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slack-notifications
            port:
              number: 8080

