apiVersion: ENC[AES256_GCM,data:rAs=,iv:ch2U0KejyN2ZV7iicCE3F3q0tDd9T/VQuY8ohSkntDw=,tag:rO6TKmZPED6/mJk/ewY7EA==,type:str]
kind: ENC[AES256_GCM,data:+hE4jGwi,iv:th0lL2Gzk0f3S2Ks/fS0eLgJtL00CATDoir8rjIXxBY=,tag:bRy5zerDFgd5bYAnbJK22A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0uSYavuPH/d7CsyvtZpTMCekPaXcRiJJEh2g,iv:xftwDQIxCQ3nSIAlxRAJOOzx3b5pAjMjfnVbk6JCuGU=,tag:L1fFRVJEDxMO5aVbgM86KQ==,type:str]
    namespace: ENC[AES256_GCM,data:9vROuNAWzbnT,iv:wxQ7fZMOy6HocJi7PpjhRxlu8hMmLx+B0tLbZDtE/ck=,tag:DMxjdv8EigK2LgAm/DTXYg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:xg3OiKZaT5faxrYOpL61t9ljIw==,iv:cfNuI2ey78e5hfjaqzmqN7OzZKi0LR9R4AG0V2Ae3eg=,tag:7gM6Rk8wTcuwPCdMfGWM+g==,type:str]
type: ENC[AES256_GCM,data:R9tmOaH0,iv:H/u34W75mUPrZCozsohN8u0u5yn6jXwXIz0kolw1BzE=,tag:nTNKXDCBZhL5p+cTEgJuXg==,type:str]
stringData:
    SLACK_TOKEN: ENC[AES256_GCM,data:YiTS2OkAtFnyhRbZqwh7/N/tEKz9G57YDbZPSrMN11A1vE1/g/kRdEjWeesp7I+kRmzWxhbDWNR8,iv:S/BCxkNUXOGt2jOPq8V4JYORcv3NT1OcSOGcRiyr2Qg=,tag:MbspvrLd9Xk6+aoiNajprg==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:sWGN7gP0+vcHaJWaoRNjsPR2LYC+4TD1GjDv9HrDY8SpTr4Kr98D0UufsH0na3ifTKy/SCs5b72yFsILbcKdR4RUIF83x0ibfrnNM93aZsSq,iv:gVKLq8bpDQfvKmd3RJur7yrdkLU4m3pKuQ0yNdiR+aM=,tag:+931LGUy1hDz+lky9gVCSw==,type:str]
    SLACK_SIGNING_SECRET: ENC[AES256_GCM,data:1Ar9xCdSnScXwLVmg+SYbMbOYC8NkhZKXaJtfLpgt1M=,iv:FJFMb8EP5Gk2jC61ICwCl1xKECrkO5z9tydrwc7/l2w=,tag:dr6DnxUNsNUAgGndX8rIbg==,type:str]
    SLACK_CLIENT_ID: ENC[AES256_GCM,data:SINikPYK8NlSQAE1YuPsMWuIzr996hmXRSWr,iv:qdm2MdOiqSdUS2idj2kb6XccynZeKW1sjlCEwNgSccQ=,tag:tqsNJZHacGGlSf2oFBgAwA==,type:str]
    SLACK_CLIENT_SECRET: ENC[AES256_GCM,data:ZEiqVad4wv1eRnLjAd8B34bve3dhXAZUnM1kTYiUDzo=,iv:9XD88pRxQe0SBhR2NJp24kMZ56TSFBcBX2THKKvITxg=,tag:6smCteQzZ//+qmYSpiKURA==,type:str]
    SLACK_VERIFICATION_TOKEN: ENC[AES256_GCM,data:o6o3zezWZemHUFJhYJtvBv8Q/sEh5vKr,iv:92tOlP1cf4TN29VUHRWxV0M6hSus7CWdN1yZJGrc7Dk=,tag:fPvwBiLspaKIHWbegm0OAA==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:96I+putx1qK1VCNTBLy0KLIPyleDScuN3XAk+iwJgvhf1jbp,iv:xGP3dc569JJpIEID6igj/2i2joYMJTTXM2mTHanBx9o=,tag:c3uoi9/jqDOlvXKvx0icbA==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:OomD932mR7bsv0vaf5ChgMqxDLTEnalqotyXyIllxgGcm+ne,iv:mC54K9w1UvYRzndArFsgUA8OHUtiGxlGprpEpxjqg4U=,tag:zxzGqNFcgWNwUNhN+EEHxg==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:2AOplzSnHBGfxEKHfCK5bEvyrR8at4GFp9dZQ6TtKzTD7qhC6ig7Xg==,iv:5uuONnh7rqsw/S0OmaD0bLbeZcZ0C2YTEk8nZ8s9GfA=,tag:cwjZUR9MtUgDhxW2k+ei2Q==,type:str]
    AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:5pvHpfzmzEKHtHiLGlovmxJdsJSqbd57qKC1e81dwFpK36fe,iv:Q9QYTFRSNF9jGtjq6DX9A2cGZvZ/gzWwVo0l0KKoNxU=,tag:L5tHwUS3WMl4j0vGTf18AQ==,type:str]
    HASADNAA_DB_USER: ENC[AES256_GCM,data:zZ/wXQzdJew=,iv:jYk1I0/hXOoWy0RdjIYMF2WmBENZG7OGK5VqrNHQZg4=,tag:SDWggEmhCqTYzM7/rq5PcQ==,type:str]
    HASADNAA_DB_PASSWORD: ENC[AES256_GCM,data:w86MPnE5r9g=,iv:OuMk722TMdVIgavHE9gIta3P9PBhGmKexGqixpMRhg0=,tag:zNpE+EDEr9gpro07k7LnZw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0pVUUJ6UE1iTXZ6WlQ2
            c0RMNWQ5SXFXM01wbmxvNFV4a1VtZG93eUZJCkNsOGN5YWtacEdkejNQc2prd0dK
            MjhwVC9hUUZWSHZwRHVGdGtnRkJTYUkKLS0tIEkzSE1iN2dGcVlNYUVGNEJwT0Qw
            MG9EbnllSjIySU00T2twOVR0QkJxUFUKrEZkFSPw5juqD3LFzZzS5XnhubGfVqj5
            RxOlb2wGkVNn/JjziTS31btFm4erICcDJgaiPrjjPezrcJrWQrtglw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T11:23:10Z"
    mac: ENC[AES256_GCM,data:PB65fMkfFm/+QbmzZxSnZmUrcbNKTW9EwW3EebdC/WLhBFInuqK2Fjt40ZT6oOvgVtdWg2Lml3q0VvuyLAFkm5iiKqB62f1ytAnxymybJPJwGdAafjUyHliMNq6Hyz9m9AKYcdqHxrERXU9MZY4qZwCtjctrefUw240RFAE09jM=,iv:IgPtmo1rWbr0GO2hENj5L7KpUHZZu8UKXkoxe9iEsrk=,tag:aekShCfAMVoHyuQMcRNE/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
