apiVersion: ENC[AES256_GCM,data:jhg=,iv:CC4W4tHI5bwshAJa4fr5mKSYGqc7MjECbT91XZ6gTJA=,tag:d+gI3yj7sqxXtwvlR5mEPg==,type:str]
kind: ENC[AES256_GCM,data:V3XTO97m,iv:aC6gZVzx1Ni6DWu2L2lBXohMIYTVJEUEuSZF7x/QMjE=,tag:t/VQgJmTxktrmwvtcDQ8dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3DFS1k9LsNTKu+TuMkGXx0tlh0wFuYEfo3j6,iv:Er7hp6aVzLe+HlWabisQhVgAzTbGnMphIPgr+YeZk2E=,tag:22xdMQHMSiI8+bnPzXim1w==,type:str]
    namespace: ENC[AES256_GCM,data:pzVyzgpKlYXD,iv:6agLEOYFF+dYmuZoy9tKvjK8rwSo+rxT7vM1HSSbCFc=,tag:E8Buo90a2l821DoFvom6oA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:kKS7l9n202/QbQ2YzuZfDbztgQ==,iv:eeYhhY8a5cG97LbBjt6m5QmvQmAGcoPYAUBR1Ez1Kx4=,tag:uaRy4dc41BZzDJ72JxB1bQ==,type:str]
type: ENC[AES256_GCM,data:k/EuVBYU,iv:ppOQPhfI3bEMrn6zhd1vk273SMBLZkQzdDtEV37eoqM=,tag:Cn5/lINgiAaU4CzP6nWgUw==,type:str]
stringData:
    SLACK_TOKEN: ENC[AES256_GCM,data:ZFYpKtgY3LWFHbOU1uDGzRz7dCkoGMFR+WdKMP81VEKGw6VRL2LMk20uvZx18uJk2IJpFj6vEOBz,iv:SFSf2E5eEXpukhG9b0dFC9S3LFcfe/KQrmWln13RjN4=,tag:5iigbfh2HU3nYXH+vO/WgQ==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:pow6GorQT9OnDKhXDELHT52AekZhCXg3SaPZFFNYCuSLNuGdwdwYVuSghGKiNu2U49J4Hf8B/B6UB5WGJadCfin9Asx5rY7D7uumkpZqUo8u,iv:nVWYHgidrzzzv1jhktvyPom9IUpY7OZPs02cqZ9M76k=,tag:hA2d63QFG2fEfGA1AIo30g==,type:str]
    SLACK_SIGNING_SECRET: ENC[AES256_GCM,data:1VGqycJayPjn/TksMInNO0eJ9Bc7AnjajeinadTtWVQ=,iv:9CeDJ4t9ppt6YvndrIJhyj5K0pXpQwWl0bnm/za/iv0=,tag:6HORkjUTzjkAup7OVy9NxQ==,type:str]
    SLACK_CLIENT_ID: ENC[AES256_GCM,data:AvvshNCNW6DsyoiB1efGBQCG3l2V7zbfKhbq,iv:uEDxxTtHC8aEjPLDO3mmLbMe4/Qf5YgllOoAxPrLCkw=,tag:6frC2CCaTJzPVABw/wm4lw==,type:str]
    SLACK_CLIENT_SECRET: ENC[AES256_GCM,data:VV2SNcRju1IPvQgTAiZuAIOGtGaVlAFOALZnbgbunSQ=,iv:7ZdRNXLtT0Y6e7LiDFd+vMNqYtaqE1chUvDSUphIFXk=,tag:6JDB00nsHVg9F9m8jYLulw==,type:str]
    SLACK_VERIFICATION_TOKEN: ENC[AES256_GCM,data:WXWTStXA9gwLwp0m3PG9wvNjEzRuSCwz,iv:t2+42tO8480Dvl07J50QmafK8S9+yFJMCZaeFVZzr1U=,tag:u+h01Ne73LfWYpOxeMyFGw==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:zPbAA5RN9sBzRPm1zpQwhMQwOO8VbcDuVe9zsJRiRuyjsuSI,iv:FV0u8Hxy1s7hOscsW+J59LZiujY3eSEy+ga8t+3G9Jw=,tag:QscSISzi1Fyd+HKRHGU90A==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:Nk3DUQzxpqLyKzwJFphfMmR1BDW1uPQjhikerMu2DIVpBUqk,iv:CEyfcPidBKTViWen5g2zja4dFSQ+pt5lKvF97oS6mVM=,tag:C+HTvM9Xl5mjkHKGrbHp7w==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:JDK30h1c+8Dgq760xZeJykjQOCjwJh/LBtAAAOZnFsuoIeP9mpYScw==,iv:22ghkS6rEfb1ddxEYjLYXEyZbzI65/Zrz9YKGrismMM=,tag:OqqvFCb6s3nTHZ0KUB4sHQ==,type:str]
    AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:sBljbADR4YfZz9bRPDdSBmvFp0lIKypnztB6bQpl/ADjMi2l,iv:snUgi+mm9vCB6QP3ZzNLE66IY2xJr0Nte56CC5heRdo=,tag:IMbeIZkMYp/PZfCWVaoAkg==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK3I3dUJZWDV5cXdHRVYz
            c3RKMzJ1OVFrY2F3MEN4ZHJtcXd4ZWt0ZkVRCmdkeGlpYitQS0ptNXhIQXRMcjhz
            WFliOWQ1Z2ZwMFdJS0pEamVBd3NXU3MKLS0tIGZMUDFaMXV0MUJWUDNLUTJJbnFo
            bXBSR1BmM3hlSmc4eXBZbWJDaVNBcEEKj6b56JNfPuA0MdHVhPF/RaP1mUsxskIa
            IClI1TvBb9RQmy+Ay6GEKtgcIjYveZ8jHIyCs/8jkXFWrZi2e8aFow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T12:31:14Z"
    mac: ENC[AES256_GCM,data:wupqjDwPIlJeyC01s69ZDm5+mNfJk5a+Rnpi+LI8Fccp3KswFRk+lIHHABpjIGMaas3Lhg+4mCRIX8J0XlF6QvxJmUsvLr/ilF+jHwPNPnh62c0GhB4EwHAGbuhTve7LqBjbwYG/glaMQ0n9wy9SFf7BhmvNBrcepLDmt7y6Rcc=,iv:4qJNwcrEUVlX0ivsHLwh4aPBuRHdtsdbj0xvzfUM64A=,tag:8oSK8Hx/1l/VziPa2yfYcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
