apiVersion: ENC[AES256_GCM,data:Vew=,iv:MemRPgYlw1OdbnOjZubsJCOLb5dPDv0hkWXg8tP0TlU=,tag:8NS50n48sJXihXvMBemnVQ==,type:str]
kind: ENC[AES256_GCM,data:i4u6nTGE,iv:3vkAdLiUqYV+qE9bWGYVEp5msbJXiG2MjkvUtmdijMw=,tag:o942wpS9mSFc7KQXUZRa8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o1HN7kzeP8kvpY1eCYzSJb2CgxAdJEqKVPP7,iv:DvawiYBfRnFsGTqpVb2gRjzaZu/+GP9hivjGYi4jWuU=,tag:cREiDostVtXOyOUot/oPvA==,type:str]
    namespace: ENC[AES256_GCM,data:78hdA9QrA9tu,iv:q5Ne4fdkSTJOGMR7AmXi/ioKi61mLYf8N0PKZbJHIDY=,tag:0Za11KtRMBfB4zHx3V623g==,type:str]
    labels:
        app: ENC[AES256_GCM,data:KXllh67R8ApawrKJi3Zy7LZBEg==,iv:LSf83cTTZKlIPJ8JxfQRzpZEOY33YIk7LsC4OLt9pnE=,tag:1M9UT1z3CQfNq0cw9+pZaA==,type:str]
type: ENC[AES256_GCM,data:Ve62QcjR,iv:S3UaLk3ezxVuQLs8yzEXdd3Fm99pv32Y8tVDOe7elWc=,tag:Agd7LLkyzUIOeMHx8QcVgQ==,type:str]
stringData:
    SLACK_TOKEN: ENC[AES256_GCM,data:OHJBE+fYRXWRtQ3VduYXCb1YGVfKw1IAOBUr1WsIvjBrsHlasomtONhibm5zqfW3G3ElGieqm8tq,iv:3kQ0bT+VLiWO8IZzwG0xN4EExHHqsMwTGmT4w3ZQgwI=,tag:6yYInW9YgyXVSlrqyKDi0Q==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:k5sYomORf0cIXpvK9RC5N7skgz9VmRSIj34Jhu5kB5WixlkqCrYDW49/k8PH7TF8fnwzPOH1eiLJ2S7T8UDqFzj3Diyj3OT3HR+5nmfa887Y,iv:ODO3ptoipf7DlLLQPsumOTcFgox89+KIq8g5JmhDD+w=,tag:w+xbx63u9ZznBfL6pehIEQ==,type:str]
    SLACK_SIGNING_SECRET: ENC[AES256_GCM,data:Uq8iIyNZk3dP0fzB+kBpxmTpsUHOjOG3jHMdeW1wkCM=,iv:WidZNyn3JaETzwpIXk+jELNY1Pj2xOeEPmSKxTT2N9Y=,tag:xYIqjviruVevS+YqHzkcyA==,type:str]
    SLACK_CLIENT_ID: ENC[AES256_GCM,data:tr1KHITh4gKDbw1D8qYgmdO3uhOcFHKM6xIT,iv:zS1M71LOnFjEsgI6ZD/pVvIJugk/+YkDuw/K5ypEDNo=,tag:3nnRdf7HbVyqZTWg9fJGDQ==,type:str]
    SLACK_CLIENT_SECRET: ENC[AES256_GCM,data:NM/hTq0l+TZudUYAaSlwocuoOD1aSxhERr9KjTBtuGw=,iv:17DAKY9KZXdJNl5XCUJyMRYVsW0dRmz7gw9Z8hVIcK4=,tag:aSQVH/Hs9krZqVbBdwub0g==,type:str]
    SLACK_VERIFICATION_TOKEN: ENC[AES256_GCM,data:U5P4qhbOoE54Z4wVTxlrbmpOOLe0naU3,iv:l+TTS0aXc40cKx6F4VTFey+8BKtCIF/bDyquzY5bAOI=,tag:2qFTcAIygAr7LzEnQIAp5w==,type:str]
    AZURE_TENANT_ID: ENC[AES256_GCM,data:bg2JhCfHevSejoygYE6n5IL7ylqXnrxN/Z5xPMxOAzLZkyXD,iv:MnAdWMdMyBG4CVOAfFn+10LWI6lNyzlvkT2C5cmNBqs=,tag:50zogS9ExIN1diycDczbPg==,type:str]
    AZURE_CLIENT_ID: ENC[AES256_GCM,data:od9KkiAYzlIlIa5bVJhXcRe6BD5uzykHFh054f8ECjQ++Arh,iv:r6DN1rxqo3qdUocAtXLmEBYcSjvCCNjhObED5h+arWI=,tag:no8Nl8PhyDoz2kKoH8J5gw==,type:str]
    AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:2Fw1QJSwHDJcHIh0vqhoq1HjA/V51pCT6L32QjSPHd/TFopz0m2Ggg==,iv:Ka2REBpRfA6q3uRsklWpGLLlZotdxx2b/y3NuGbMfTc=,tag:IoEJSeZ+bxtq76bOGJfG/Q==,type:str]
    AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:++sStiqgx2Ufe+4mEBJHPciyxavY02cd3t/hoK/i6e40oKer,iv:SJRs6ZzVj9AaBo0+HOeGmb1eu+6GWHBNAejccdG4PYw=,tag:0mrgQkRq5/Go2UNvK4wXfw==,type:str]
    HASADNAA_DB_USER: ENC[AES256_GCM,data:dPLuUKHzkhk=,iv:QJWXvrlopVec/fLHNNPitpcci9SvdL++AiUgE+jSKKA=,tag:QwIszrchIBscIT0kjv2Jvg==,type:str]
    HASADNAA_DB_PASSWORD: ENC[AES256_GCM,data:1gi/yNA7G9w=,iv:1PgSZOZhw7Ekh5dxFBuM+XLEE9Ys8FTGaC6VTfC/TSs=,tag:g4aIATmpatY+GLOR9hZGfQ==,type:str]
    PG_BACKUP_STORAGE_ACCOUNT: ENC[AES256_GCM,data:CQIzC69peAkUhCATuCjumL8mAw==,iv:gFQopqiOgNTH3ZJZGQ2Zz7PIutx4i13fl8PGLPQ+kXQ=,tag:k8/Q+9uR1Llt2gA0cOBK7w==,type:str]
    PG_BACKUP_STORAGE_KEY: ENC[AES256_GCM,data:AYqL1pIt5sJHmMIaA0Qujq4YyKrzxPOWp26sx3jSzNdMRk8KmEgqEvQV8F0r75ikPrfJ0P2PPlPbakgPybUVC6prVGgZ7lNNXkwcV7ZnnvX/2f8WHeZttQ==,iv:eCn6W8MRTMAKvSHAriI2a/F0hK2a1E3nr0X5+eYywlQ=,tag:KkeZNITXtEHTvU/5RCkpsQ==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRnpGcE52M2RDNk43V0xE
            dGxxL2JzN3RTVHZ2UVdzR01ubVlvYTBnUmxvCis4Y2JIKy9zWUV1R2Zhc21MaC90
            TVJERURmWVpaekZ1ZXo2MlhSRXVyN28KLS0tIFJ1ZVIwemdQTEtuMnNCM0tINzF5
            NEdhdHRyRW9tMnNma2tZYUpFWDJiY1UKNNFBGi/R/aCSBEVYd3X5m7DVy3B7sKlX
            6cIQcjBxkJ9gnodRWFb+AKVSCFCpF0lAq/XqEFQHL3EDaJ5rscfDPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T09:23:52Z"
    mac: ENC[AES256_GCM,data:SRqPeTtEhVz+JnyRb/AC2fVS+EUxRYB7VTrmtasfE+xT/nM6G1+jpCCyF/KWMocwNvFuw+7USiqb3cXSlR0VYuDtTim/Iz1IhV3a7HzD27NxcCFJumNIGNa6ZZHSZyoDfxuJ2bhDFUUaAOdjDcwl6Il1ndo91gKuGJEnnE83dhE=,iv:HhHjc9TKQjZpkPAu9qf9wF4phnl9aAdPhAlIftN3tcw=,tag:nKlGsLddktXO1bqgFoacEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
