apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-tunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: main
    path: argocd-tunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

