apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-demo-be
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: argo-rollouts-demo-be

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts-demo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
