apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blutag-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eladhayun/gitops
    targetRevision: main
    path: blutag-website
  destination:
    server: https://kubernetes.default.svc
    namespace: blutag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

