apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debug-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: debug-server

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

