apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dirtbike-specialist
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: dirtbike-specialist
  destination:
    server: https://kubernetes.default.svc
    namespace: dirtbike-specialist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
