apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen-rag-qdrant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: gen-rag-qdrant
  destination:
    server: https://kubernetes.default.svc
    namespace: gen-rag
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
