apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: ids-backend

  destination:
    server: https://kubernetes.default.svc
    namespace: ids

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
