apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linux-shell
  namespace: argocd
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: default

  source:
    repoURL: https://github.com/eladhayun/gitops.git
    targetRevision: HEAD
    path: linux-shell

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true