apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.1.0
    helm:
      releaseName: mariadb
      values: |
        auth:
          rootPassword: ids-mariadb-root-password
          database: ids_embeddings
          username: ids_user
          password: ids-embeddings-password
        
        primary:
          persistence:
            enabled: true
            size: 50Gi
            storageClass: managed-csi
          
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
          
          configuration: |-
            [mysqld]
            max_connections=200
            innodb_buffer_pool_size=1G
            innodb_log_file_size=256M
            max_allowed_packet=256M
        
        metrics:
          enabled: false
        
        volumePermissions:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: ids
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

