apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ids-qdrant
  labels:
    app: ids-qdrant
spec:
  serviceName: ids-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: ids-qdrant
  template:
    metadata:
      labels:
        app: ids-qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.12.4
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        env:
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__STORAGE__STORAGE_PATH
          value: /qdrant/storage
        - name: QDRANT__CLUSTER__ENABLED
          value: "false"
        volumeMounts:
        - name: qdrant-data
          mountPath: /qdrant/storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6333
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 2
  volumeClaimTemplates:
  - metadata:
      name: qdrant-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
