apiVersion: ENC[AES256_GCM,data:RI4=,iv:oy45KRmD2OFVgfU/WhszAcRq1eKoOpwNPmPFHYtCZd8=,tag:+xQvKs6FoyD9Ugj/ToeauA==,type:str]
data:
    ANPR_AZURE_ACCESS_KEY: ENC[AES256_GCM,data:GBnGnGJK27sCdGHMotVrTPR99uKi3hnk/JT6pW3SHc5W+ptJ/CEOen2ZotELyy9e+CerFESkdQXZFfKhfoXa6wwr9r19ln3Bf5t2ljXIk8Nvw/KF2ym7GqXvRZ9EA+5vSU91XZC1z+l3Q/n3aYJQ/XaLKJ9N17CH,iv:prNxu9JUvKkLE/xt5mgOOIXBj7hKgandq16P38ywOgE=,tag:++w+Ru+D6CQcelapwMgYBw==,type:str]
    ANPR_AZURE_ACCOUNT: ENC[AES256_GCM,data:LUmGJecMuJX+NvgZQ277AknBkMUGi+iBKfEs7A==,iv:cGaM8zGdwp9PfSv2OPb5SEhjIBL5vhcdUb2XQ01bN0g=,tag:6n8E0fjpXfDCnHvVvij/qg==,type:str]
    ANPR_EDGE_TOKEN: ENC[AES256_GCM,data:aqsoUdxnRvfl/CR5N2VVFDuvavW5SalzmpC6fO0sCmfihmgHv9k2doVFOYfrNR8OT7imjLUReEu8T8FaZLiwsruAZYheoPuB4hc3rBXK7RTDrA9JX6tUqQ==,iv:+PFokv+ArvKXHLaK1rG3EzsrUcssqq5EjyoNxoBwQuc=,tag:KasSfey6yuV5x4iQ0eg99A==,type:str]
    ANPR_QUERY_TOKEN: ENC[AES256_GCM,data:IKyklI864ek4sX6tEkNx/bT8Y/8NAxE3Ofstf5Zn+fGw8X7c1Ith7aeDQ3/s5U6sVEdTRYDa3OrCoDX4r5OgfrJxoQR0CXyqXw3sRJKRU3p6/RsMtscCeQ==,iv:xyPKNZV6CeqUjbAvOa/v32hVQ/Jni+FtrtMYmEqZcZ0=,tag:sk5b4vurT0VJrfU7dTtTaw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:a3BE7dA2Mm5H/owcd1N9gqOKL0NB0i/QhojdOskYS0ZTEe1HmI24snfzC4jVq6XtfZjoDehOuxxuPXxFl28W+KBXFh8o8pgeN8JYM7tpVlwR+5ZwEfTkAngsz+XgfN5Cik/D3qne8BzdNnDHAPYc4Bl2Sqhd2TAtLZ2vh6o+c2iiszjJXsztyaIKwkB+T4wt3HdPObOD3u/oItO7llLbM4dJgIzNM7HEwiutKQ==,iv:+/ZoxFElzqxBtCx0Hmm7g0HysZp5OtCzVdz1+1D56cQ=,tag:5JRseQUlPnSYGwWWJoQztw==,type:str]
    ANPR_SLACK_NOTIFICATIONS_TOKEN: ENC[AES256_GCM,data:X237kGI90lenQq2YzGpTWYWn81MhDBUVY0yVs6ot5fCgiQCI1YdXv9jY5VP0jcWm6FnQDojvsN9BdsHIYKh6CQbdWRWZ73rtQhjLI2MaV2gTnsau6teF/tc=,iv:UgqOZvYC9OFb2jcg9p28stsem3qylDZre64EKWZ716E=,tag:MKpG71N3LyYMcsJT99/9pg==,type:str]
kind: ENC[AES256_GCM,data:GyVTnF9e,iv:IE6ApWQRO+XPE0RCMSPxZwghdcrJzhfeRCh4RDzYy8M=,tag:wmLQAn8wy+xcbD+0xtLnZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z03dB/PCNOZzUJwzm1M+6Tpt,iv:nmdLUytrcREAnOmZnKSMLU2vnIpxKqPh4p7bTqrktdM=,tag:150o8EcdNSrdGYpqR/LN0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUZHV0N5MWpiMTJuTW5N
            L3BzY2pUVW5RNlFuOTB5ZHFUclVFaGoyNnpZClFEampsNGx5eHRsYmZnbWNjYnd2
            aGpWVXNiNU90MmRobWVqa1BVdXAxU3MKLS0tIDRhd25UNE5UTmVTdktVemlaaTd5
            eUpHSWdhNWpuaXd5VUcvbmFDZTk4SDAKvPLMfJ55hSari2xHRXbQS4Gpeu8snR7q
            j+hpDFlTqDgWZpqjF/QEOQQGRFvFJ+K8w/Cr/A8ftrOhvzYohinAZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-08-30T10:44:14Z"
    mac: ENC[AES256_GCM,data:6T5NlmskEZ1B/WD4aGM+3IIVr24wfusqRk0TDDFI67mUFWgW5rZhye62vNdjKdWIiB/gIgydRTGtE2c8Rd5eu21kCF98tvI5Vh3MllyjHwvnKaL+9jYr2IF7Oe3nNM/8hSFWwaJX91H3vk6OEtyzj+NQ4pk1zTnfiWk4QU1SUR4=,iv:4cPhJbaOugPfPzJBMBTO7zZGBjnE9Pw92v33cQh8tzM=,tag:XVKd4NH74oKcqoYietBHHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
