---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: padel-booking
resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- network-policy.yaml
generators:
- secrets-generator.yaml
images:
- name: padel-booking
  newName: prodacr1234.azurecr.io/padel-booking
  newTag: main-a46c2991a7ec8442b74f0b6f07e31410fba15f85
  digest: sha256:7522cab224f6cb859062f3a349f7e4e9610129306a91231c475e77bcabdb4a72
