apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: padel-private-state
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
