---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 6
    failureLimit: 1
    provider:
      web:
        url: http://argo-rollouts-demo-be-service.demo.svc.cluster.local:80/api/metrics
        # Calculate error rate as percentage: (500 errors / total requests) * 100
        # If no 500 errors exist, return 0% instead of division by zero
        # Example: if 2 errors out of 10 requests, returns 20%
        jsonPath: "{$.http_requests_total['/api/check']['500'] ? ($.http_requests_total['/api/check']['500'] / ($.http_requests_total['/api/check']['200'] + $.http_requests_total['/api/check']['500']) * 100) : 0}"
    successCondition: result[0] < 50