---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 10s
    count: 10
    failureLimit: 1
    provider:
      web:
        url: http://argo-rollouts-demo-be-service.demo.svc.cluster.local:80/api/metrics
        jsonPath: "{$.500}"
    successCondition: result < 20
  - name: total-requests
    interval: 10s
    count: 10
    failureLimit: 4
    provider:
      web:
        url: http://argo-rollouts-demo-be-service.demo.svc.cluster.local:80/api/metrics
        jsonPath: "{$.200}"
    successCondition: result >= 0