---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
  namespace: demo
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 6
    failureLimit: 1
    provider:
      prometheus:
        address: http://argo-rollouts-demo-be-service.demo.svc.cluster.local/api/metrics
        query: |
          sum(rate(http_requests_total{endpoint="/api/check",status_code!="200"}[30s])) / 
          sum(rate(http_requests_total{endpoint="/api/check"}[30s])) * 100
    successCondition: result[0] < 50