---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollouts-demo-be
  namespace: argo-rollouts-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: argo-rollouts-demo-be
  template:
    metadata:
      labels:
        app: argo-rollouts-demo-be
    spec:
      containers:
        - name: argo-rollouts-demo-be
          image: prodacr1234.azurecr.io/argo-rollouts-demo-be:main-3f021e5
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 2
          envFrom:
            - configMapRef:
                name: argo-rollouts-demo-be-config
  strategy:
    canary:
      analysis:
        templates:
        - templateName: error-rate-check
        startingStep: 1
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
