apiVersion: ENC[AES256_GCM,data:d+I=,iv:smOYSYzH7YOoMWoA8KCDaVI3y6kPB1rU2OdFcfl9MGs=,tag:ci494WVsKCH+gv+3aHesMA==,type:str]
kind: ENC[AES256_GCM,data:Q55YojJW,iv:ibre1LRJVNMMauGuuU6SHY1UZuZNpeNMYc942FqM0r8=,tag:on16brYrP6yFMTNlrZ9tLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lH+JWTg3zYTtb/IRl+c/IQPVBCw=,iv:jm4mcsj+zAskNlDDDBgbw4nLv8l7S6aD/2gxSoPnRfk=,tag:9GZrOFm60pP9JSRVoi0RaA==,type:str]
    namespace: ENC[AES256_GCM,data:gOvdgm26oVeW9Zep,iv:lmsZkV3p/MXixINW5SSbIlVa69fBD+jr2kXapMJzOks=,tag:7LM9MRkjL+MVfpkxS3BZIQ==,type:str]
type: ENC[AES256_GCM,data:Vh2NK16p,iv:Uh2Eh/rFXXSoWPM67yOR1Ivna+4Df7n54KIyDeu9bXM=,tag:A0IE9wjz3PRqnYiMnX9jJQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:55FJ3RoLHvk8c6kL+02wrsvwBj3+8xmPdlCg8A2DWV9vK2PT6/NZ8g==,iv:LxgTeV8pGmsnA0wB+bNf0U1ZZd/WnwK5auONRyrbLTk=,tag:udMc0P0EDlLr34fhVgmBlw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVStXNUpUSE1qMjg4bTR4
            VG5xeGU0ZUNTVVdkb1B1STBFR1VIMmdNWGtZCnZIemxHSHhlL1JLWkNUK2Y5QnRE
            Wkl4czVPb09QQVZ4UlcyS1JsTno3NTgKLS0tIGtNaXRVdzVnQndndU92eGJLVGRk
            WW5UNzdFbHdaWHkxOGk0N0F4SGVFekEKOnsZMxhTvVR7y3hOpPenJUzQYqrUVon4
            9gDkyo9ln3FwwtRySdSfAcRsdvSZfwlbKcvzEoLKGOAifOy9UOMyNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:05:08Z"
    mac: ENC[AES256_GCM,data:9Kef0ZeeDxtH5YLkQ9I4qM5t8QfkJRXgcprJF+mJlOmKfZ8uc+m5y4b2C4qZellHqVKjgg8GolyQe8AHY9UWRqaz202vN8khIqk/y1iGEEouzLlpTHdXBjPRWHvxpYFRSGjYbg+UFqPAj78z+K8etQ//MAJLgFkwO/WF36wG0Mo=,iv:vBLtqx1xo/fcGGogSN1PcLs+KNZCHHApgEVXpHdWhag=,tag:3/xSYPvBUV5hqplcT9Y3Tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
