apiVersion: ENC[AES256_GCM,data:ClY=,iv:4T4CM4MTWFT+Uubw+pGCEP3WJRdQsslJCbglaMosvWg=,tag:rcwtO1h2guyxU0nUxuIzcg==,type:str]
kind: ENC[AES256_GCM,data:fX/Z2obf,iv:+iaSGizEKUtjdh6dYHG027DUwSgiBhc+QahJiVTMCm0=,tag:t5VFCfIzHrNqUtlHZk7ljQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZY1wGKvVuAWf/+rS7L5zxKUPeA==,iv:9j0aZ7K17tYR1crjAbsOYj+ENbo7MeKFRwWDLE3Igpw=,tag:4erH6Y6P1PzC7HAphy/KXQ==,type:str]
    namespace: ENC[AES256_GCM,data:PRhR,iv:fGXSWrpZXNgE4/8NV1Bsk1NXRSJZDBcqvy/47Ixtj5A=,tag:eED4jVM2UjRxSSNX225b3g==,type:str]
type: ENC[AES256_GCM,data:BRP8VEhy,iv:IkL5q/glt98RtKrXJ4ruFg9+QNieBeZ2ul5iMN926pg=,tag:fbKfcKkzcfHM4ntvSbW+uw==,type:str]
stringData:
    postgres-user: ENC[AES256_GCM,data:ynd111tufSE=,iv:InyRbwxOAvb2Qsvu+n6fv6mu2e49UT4fpaygQF9qYAM=,tag:j0sCjbHKMB8+ORqvlciTZQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:ugJML9oqsbK85pM6iyf8srR4fPc3fXWQrcmlMQ==,iv:Hu/1OxNBiH3U4pPJcxdz6W1MOQyF5LpfVhkEkuYV71U=,tag:nXtIg5cCQ6rCp8EAH2Mh+g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:KL0oGr6rh83fEYTbu3eU3ziVk7H33jxAXtJvyXOaObMiNn/b+6YkeajEGcR9j+4rTHAMWOXlbsDUnxxRS9av1dwS7yObPktTarO68ewfPpqEuzV16PcdgRx3QUTlZyAUV2/lqzW+2IkYL4BKyTzsy0mRRLB++mN7R0opBKDf1A==,iv:Rw2xHPLDm/6EVD09RdEk3QHQC1DQCDOqDK9v61kVGNE=,tag:nFqnURM94AIBlj1N45WnQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmpXbjRrRlN6TkxVVFFU
            ZTM1V0tmY3k1Zk14RDAwYnE3ZG9ydW50NFZRCm10MzJNdk02TEpzY1JQd3VVSC91
            MmpUQmhXbE9HL2lHY05vcmtzT2hkalkKLS0tIFZKdUxpUHN2aTUyRVEwd0xUbXo3
            Z2VxSnhwTHNKaHdkRm5EUSt1V1g3N0kKinZNz2WMtAQXe+Xzar7VJjYO33V0zMLC
            ocMVQoj4+83u/bJ0BW/vDfeH9jgMKUsiRleOwg8FocLCKAsUGHvwJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-09-01T07:22:31Z"
    mac: ENC[AES256_GCM,data:CDbU7s8LBJF7fDTJURLqNcMBEiS35QWYtghyLVn7vvWStID4wiC6vBDBcj8HBi9y9XfS209pWm5Si1CD9xRWyghMU2ISdjVL+H6nb8d37JeURd7kRrfSqOgXkz1C0ALdoh1UeeifW4wDpEpX0JTIac/QXOR10YwnnIgYVHMuyqw=,iv:nO+LhGnbjaaudws6MS5/d6XEuqjvwFzVC3VEGkjWxSM=,tag:LJtjQQarV0OVyp3NUTjPag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
