apiVersion: batch/v1
kind: Job
metadata:
  name: ids-init-embeddings
  labels:
    app: ids
    component: init-embeddings
spec:
  # Allow the job to be manually triggered and retried
  completions: 1
  parallelism: 1
  # Don't automatically delete completed jobs - keep for debugging
  ttlSecondsAfterFinished: 86400  # Keep for 24 hours
  backoffLimit: 3  # Retry up to 3 times on failure
  template:
    metadata:
      labels:
        app: ids
        component: init-embeddings
    spec:
      serviceAccountName: ids-backend
      restartPolicy: OnFailure  # Allow retries on failure
      initContainers:
      - name: ssh-connectivity-check
        image: alpine/socat:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing SSH client and netcat..."
          apk add --no-cache openssh-client netcat-openbsd &&
          mkdir -p /root/.ssh &&
          cp /etc/ssh-key/ssh-private-key /root/.ssh/id_rsa &&
          chmod 600 /root/.ssh/id_rsa &&
          echo "StrictHostKeyChecking no" > /root/.ssh/config &&
          echo "Testing SSH connectivity to ${SSH_HOST}:${SSH_PORT}..." &&
          ssh -o ConnectTimeout=10 -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "echo 'SSH connection successful'" &&
          echo "SSH connectivity verified successfully"
        env:
        - name: SSH_HOST
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_HOST
        - name: SSH_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_PORT
        - name: SSH_USER
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_USER
        volumeMounts:
        - name: ssh-key
          mountPath: /etc/ssh-key
          readOnly: true
        - name: shared-data
          mountPath: /shared
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      containers:
      # SSH tunnel sidecar container
      - name: ssh-tunnel
        image: alpine/socat:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache openssh-client netcat-openbsd &&
          mkdir -p /root/.ssh &&
          cp /etc/ssh-key/ssh-private-key /root/.ssh/id_rsa &&
          chmod 600 /root/.ssh/id_rsa &&
          echo "StrictHostKeyChecking no" > /root/.ssh/config &&
          echo "Starting SSH tunnel..." &&
          ssh -N -L ${LOCAL_PORT}:${REMOTE_HOST}:${REMOTE_PORT} -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} &
          SSH_PID=$! &&
          echo "SSH tunnel started with PID $SSH_PID" &&
          echo "Waiting for tunnel to be ready..." &&
          for i in $(seq 1 30); do
            if nc -z localhost ${LOCAL_PORT}; then
              echo "SSH tunnel is ready!" &&
              touch /shared/tunnel-ready &&
              break
            fi
            echo "Attempt $i/30: Tunnel not ready yet, waiting..." &&
            sleep 1
          done &&
          if [ ! -f /shared/tunnel-ready ]; then
            echo "ERROR: SSH tunnel failed to become ready after 30 seconds" &&
            exit 1
          fi &&
          echo "SSH tunnel established successfully, keeping it alive..." &&
          wait $SSH_PID
        env:
        - name: SSH_HOST
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_HOST
        - name: SSH_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_PORT
        - name: SSH_USER
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: SSH_USER
        - name: LOCAL_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: LOCAL_PORT
        - name: REMOTE_HOST
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: REMOTE_HOST
        - name: REMOTE_PORT
          valueFrom:
            configMapKeyRef:
              name: ids-config
              key: REMOTE_PORT
        volumeMounts:
        - name: ssh-key
          mountPath: /etc/ssh-key
          readOnly: true
        - name: shared-data
          mountPath: /shared
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
      # Init embeddings container - runs once and exits
      - name: init-embeddings
        image: prodacr1234.azurecr.io/ids:main-f964066
        command: ["/home/appuser/init-embeddings-write", "--once"]
        env:
        - name: WAIT_FOR_TUNNEL
          value: "true"
        - name: EMBEDDINGS_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ids-postgres-secret
              key: DATABASE_URL
        envFrom:
        - configMapRef:
            name: ids-config
        - secretRef:
            name: ids-secrets
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: ssh-key
        secret:
          secretName: ids-secrets
          items:
          - key: SSH_PRIVATE_KEY
            path: ssh-private-key
          defaultMode: 0600
      - name: shared-data
        emptyDir: {}
