apiVersion: batch/v1
kind: CronJob
metadata:
  name: ids-init-embeddings
  labels:
    app: ids
    component: init-embeddings
spec:
  # Run daily at midnight UTC to check for product changes
  schedule: "0 0 * * *"
  # Keep last 3 successful jobs and 1 failed job
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid  # Don't run multiple jobs at the same time
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 86400  # Keep for 24 hours
      backoffLimit: 2  # Retry up to 2 times on failure
      template:
        metadata:
          labels:
            app: ids
            component: init-embeddings
        spec:
          serviceAccountName: ids-backend
          restartPolicy: OnFailure
          initContainers:
          - name: ssh-connectivity-check
            image: prodacr1234.azurecr.io/ids-ssh-tunnel:latest
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /root/.ssh &&
              cp /etc/ssh-key/ssh-private-key /root/.ssh/id_rsa &&
              chmod 600 /root/.ssh/id_rsa &&
              echo "StrictHostKeyChecking no" > /root/.ssh/config &&
              echo "Testing SSH connectivity to ${SSH_HOST}:${SSH_PORT}..." &&
              ssh -o ConnectTimeout=10 -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "echo 'SSH connection successful'" &&
              echo "SSH connectivity verified successfully"
            env:
            - name: SSH_HOST
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_HOST
            - name: SSH_PORT
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_PORT
            - name: SSH_USER
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_USER
            volumeMounts:
            - name: ssh-key
              mountPath: /etc/ssh-key
              readOnly: true
            - name: shared-data
              mountPath: /shared
            resources:
              requests:
                memory: "16Mi"
                cpu: "5m"
              limits:
                memory: "32Mi"
                cpu: "25m"
          containers:
          # SSH tunnel sidecar container
          - name: ssh-tunnel
            image: prodacr1234.azurecr.io/ids-ssh-tunnel:latest
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /root/.ssh &&
              cp /etc/ssh-key/ssh-private-key /root/.ssh/id_rsa &&
              chmod 600 /root/.ssh/id_rsa &&
              echo "StrictHostKeyChecking no" > /root/.ssh/config &&
              echo "Starting SSH tunnel..." &&
              ssh -N -L ${LOCAL_PORT}:${REMOTE_HOST}:${REMOTE_PORT} -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} &
              SSH_PID=$! &&
              echo "SSH tunnel started with PID $SSH_PID" &&
              echo "Waiting for tunnel to be ready..." &&
              for i in $(seq 1 30); do
                if nc -z localhost ${LOCAL_PORT}; then
                  echo "SSH tunnel is ready!" &&
                  touch /shared/tunnel-ready &&
                  break
                fi
                echo "Attempt $i/30: Tunnel not ready yet, waiting..." &&
                sleep 1
              done &&
              if [ ! -f /shared/tunnel-ready ]; then
                echo "ERROR: SSH tunnel failed to become ready after 30 seconds" &&
                exit 1
              fi &&
              echo "SSH tunnel established successfully, monitoring for job completion..." &&
              while kill -0 $SSH_PID 2>/dev/null; do
                if [ -f /shared/job-done ]; then
                  echo "Job completed signal received, shutting down SSH tunnel..." &&
                  kill $SSH_PID 2>/dev/null &&
                  exit 0
                fi
                sleep 2
              done &&
              echo "SSH tunnel process ended"
            env:
            - name: SSH_HOST
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_HOST
            - name: SSH_PORT
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_PORT
            - name: SSH_USER
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: SSH_USER
            - name: LOCAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: LOCAL_PORT
            - name: REMOTE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: REMOTE_HOST
            - name: REMOTE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ids-config
                  key: REMOTE_PORT
            volumeMounts:
            - name: ssh-key
              mountPath: /etc/ssh-key
              readOnly: true
            - name: shared-data
              mountPath: /shared
            resources:
              requests:
                memory: "16Mi"
                cpu: "5m"
              limits:
                memory: "64Mi"
                cpu: "25m"
          # Init embeddings container - runs once and exits
          - name: init-embeddings
            image: prodacr1234.azurecr.io/ids:main-e386fab
            command:
            - /bin/sh
            - -c
            - |
              /home/appuser/init-embeddings-write --once
              EXIT_CODE=$?
              touch /shared/job-done
              exit $EXIT_CODE
            env:
            - name: WAIT_FOR_TUNNEL
              value: "true"
            - name: EMBEDDINGS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ids-postgres-secret
                  key: DATABASE_URL
            envFrom:
            - configMapRef:
                name: ids-config
            - secretRef:
                name: ids-secrets
            volumeMounts:
            - name: shared-data
              mountPath: /shared
            resources:
              requests:
                memory: "64Mi"
                cpu: "10m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: ssh-key
            secret:
              secretName: ids-secrets
              items:
              - key: SSH_PRIVATE_KEY
                path: ssh-private-key
              defaultMode: 0600
          - name: shared-data
            emptyDir: {}
