apiVersion: ENC[AES256_GCM,data:nF4=,iv:b7e9fgUGOS0YoeFVVQCli0oH6DEqYUdRG1OSfAqpoLU=,tag:pRlv9vQ4QHVpCuG2IEY3uQ==,type:str]
kind: ENC[AES256_GCM,data:Fe2baF76,iv:xTqQJnx/JmougyUjBF9JEyiaA9y0avSvRaIj7KdRua0=,tag:setZdQoO5IuzYyeQTbFZFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b5pLhYS8zkrgu613Ec+0oGCtMNN6W+MjuQ==,iv:jK18KlHDpkcLHVDPE5ORFr+VigFzCYOfajVGP9vL+3o=,tag:qGDl34MH3M8MMKwNulCOaw==,type:str]
    namespace: ENC[AES256_GCM,data:d+ZD0X57jQzB,iv:EvgI4ZDJsGabvR4aNOPkV34gecMAFKj7OZj7jobIVVU=,tag:h62W+Zylh/b4mcY/YFBj/g==,type:str]
stringData:
    postgres-user: ENC[AES256_GCM,data:MTwUylIP5zv/,iv:ijZvFkrknFKRgDjRE7X51ixu+ZNmChgleWDjk+jer1I=,tag:0+wixCtZGxk2YvZSaxhRAw==,type:str]
    postgres-password: ENC[AES256_GCM,data:espAgVAstx5DquvaIw9iGv5LvNfJnvXo+WmghrwATNQ=,iv:dIViwrnZRUsFFTApjS0PvlU6T7CnKBzJhxx7yAhh3A4=,tag:okt0BzfFKcT58Vz8TR73gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcWVoSWJyN3NjeEU2TTY2
            Wmo3eE1ra0JITUphVENuSEpOa1d6LzYxR1dRCjVNT2pONXlLUDdVSHR5SzZadlly
            c3A2RVFRZnBNcW00QktjRGRPaFRSSUEKLS0tIDd1a0RTREtPdG5PN3N4ZDc0cElD
            Skp4b3RHTzNnT3dWSldVOVF2TytrY0EK8cexuDbkC6GN8MvTLbWlVAqZUWuTs7Jv
            LGeLt1puB7TSyUUQlZTS1RTeNBMtc/NEnoYPxLJ1Vk2higfjTD6tSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
    lastmodified: "2026-06-06T11:12:24Z"
    mac: ENC[AES256_GCM,data:8Fcu7drC8uJUzDXCcWZ6J+Qbsi2q2Bs+wY9KA3r6hTeyFZfxhwCQRVwGwAMXawqMfwR8OnpxsDX1x81LGQknDqSEiPkvD1pVULJ4wKCmNd/W0fgc0nnVBjwPJi1wqc1jjcDG/CtDPSvj98t6Mh3TL9q9xpJBTSYFvSJuEfymzq4=,iv:KQUzW8KUR1zzQNTEm1VAGBECN9Iloex+cMSts6Rw2Q8=,tag:d77r463MnFxuWa00vFkRaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
