apiVersion: v1
kind: Service
metadata:
  name: trainings-postgres
  labels:
    app: trainings-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: trainings-postgres
  clusterIP: None
