apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
  - service-monitor.yaml

namespace: demo

patches:
  - path: nginx-config-patch.yaml
    target:
      kind: ConfigMap
      name: ingress-nginx-controller
  - path: service-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
