apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
data:
  enable-metrics: "true"
  enable-prometheus-metrics: "true"
  prometheus-port: "10254"
  enable-vts-status: "true"
  enable-opentelemetry: "true"
  metrics-per-host: "false"