apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
spec:
  ports:
    - name: metrics
      port: 10254
      targetPort: metrics
      protocol: TCP 