apiVersion: batch/v1
kind: CronJob
metadata:
  name: email-import-job-cleanup
  namespace: ids
  labels:
    app: email-import-cleanup
spec:
  # Run every 6 hours (cost optimized)
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: email-import-cleanup-sa
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - |
                set -e
                echo "===== Email Import Job Cleanup ====="
                echo "Looking for completed email import jobs..."
                
                # Get all jobs with their creation timestamp
                ALL_JOBS=$(kubectl get jobs -n ids -l app=email-import \
                  -o json 2>/dev/null || echo '{"items":[]}')
                
                # Extract completed jobs (status.succeeded >= 1)
                COMPLETED_JOBS=$(echo "$ALL_JOBS" | grep -q '"items"' && \
                  echo "$ALL_JOBS" | grep -o '"name":"email-import-[0-9]*"' | \
                  sed 's/"name":"//;s/"$//' || echo "")
                
                if [ -z "$COMPLETED_JOBS" ]; then
                  echo "No completed jobs found. Nothing to clean up."
                  
                  # Clean up failed jobs
                  echo ""
                  echo "Checking for failed jobs..."
                  FAILED_JOBS=$(kubectl get jobs -n ids -l app=email-import \
                    -o jsonpath='{range .items[?(@.status.failed>=1)]}{.metadata.name}{"\n"}{end}' 2>/dev/null || echo "")
                  
                  if [ -n "$FAILED_JOBS" ]; then
                    echo "Deleting failed jobs:"
                    echo "$FAILED_JOBS" | while read job; do
                      if [ -n "$job" ]; then
                        echo "  - Deleting failed job: $job"
                        kubectl delete job "$job" -n ids --ignore-not-found=true
                      fi
                    done
                  else
                    echo "No failed jobs to delete."
                  fi
                  
                  exit 0
                fi
                
                # Count completed jobs
                JOB_COUNT=$(echo "$COMPLETED_JOBS" | wc -l | tr -d ' ')
                echo "Found $JOB_COUNT completed job(s)"
                
                if [ "$JOB_COUNT" -le 1 ]; then
                  echo "Only 1 completed job. Keeping it."
                  exit 0
                fi
                
                # Keep the latest (highest timestamp), delete the rest
                LATEST_JOB=$(echo "$COMPLETED_JOBS" | sort -r | head -1)
                echo "Keeping latest job: $LATEST_JOB"
                
                echo "$COMPLETED_JOBS" | while read job; do
                  if [ -n "$job" ] && [ "$job" != "$LATEST_JOB" ]; then
                    echo "  - Deleting old job: $job"
                    kubectl delete job "$job" -n ids --ignore-not-found=true
                  fi
                done
                
                echo "===== Cleanup Complete ====="
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"

