apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-data-pvc
  namespace: ids
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-csi

