apiVersion: ENC[AES256_GCM,data:qLk=,iv:OOq5Kt8E/Pbghy8JM4ksW7E8wCoFIQtVfSuCvpmcee8=,tag:46nBDQ460l4jByhXtmYjIg==,type:str]
kind: ENC[AES256_GCM,data:aGh8xCRU,iv:5qr5Plyh7EG74bq5KmYUud0Pn1yh1rTnDb0wsAd2ZsY=,tag:l819wmH2yl37lP9aJSKPjA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Fr+HU+Q4e0Hyrk3ZQ0QDX3tObrE=,iv:bkzkSr1qjPsakoqZLN83EDSo3CGdtUc5gAjTpvtHj98=,tag:jbaPLi0FY0T7ci6rrx0vRQ==,type:str]
    namespace: ENC[AES256_GCM,data:hq9udognKw==,iv:pVO4asGgvFaKHHWRrP2cj3fo38RAlJaVW7ktlmn0k6A=,tag:KC5OtpPYfIGXXiI/jqxY0A==,type:str]
type: ENC[AES256_GCM,data:u7GPK8F1,iv:fdFblkLIKIdUElEnnwQluk1OkiX/RfEAafYg1WQkyS8=,tag:BVfAo+qSO52SCMixH2lfFA==,type:str]
stringData:
    storage-account-name: ENC[AES256_GCM,data:yl9yHAdCYecDJAarm3L0qcFf1w==,iv:UcoBIWyp/EyL/20WK9gpYq8cG9vzhpGy03lwBwDFkWI=,tag:OCW4rnobc/NaZN02lZ80fQ==,type:str]
    storage-account-key: ENC[AES256_GCM,data:uz2tfTOY2OoRIcne0MI3Rrk67XO6eHHOpgcuuru2I2MJ0m0zr4BCfcGFX9Q5n5YeD8Mr3eqxcS0oiXKjPjva1Mocf3GwLXLXn4XX/pCXHtAizj9mAqJ2IQ==,iv:yBHp1VOaL54XqGYForLz1An2JXUz5ip6c68zsABI19A=,tag:TotLsHPiBc0avVrrph41/g==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M1dvWGhoL3FSQjJ4SGhE
            aWU1MzBhdlNzN0VJbnAwbnZmRUo1V1lsZUhNCitpLy9ZbFh1eHNPaHozM2dNTlRC
            SGVoOHZQNnpkMVFuUjhFT3pWRzB0ZG8KLS0tIDUyNVFxK3BmY1kxSzBVN1J1ZmpQ
            RVNQTzNmUjFlazNHTWNnZTVxTjg1Sk0Kg9IMndHYKqdx3OfPFel/vgTLepAKSwDi
            TBDFObeSMY2eAx+q6cJEKAZcteUOv2/5N1n+eqZ27Nmn8ZTI3KSyKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T10:05:16Z"
    mac: ENC[AES256_GCM,data:P0chhnsjJwk4/DD03+MhBcpUMfi0orVSnWIup0sh6TM41cfzjWSD6f1ZkeihUdMw+Pu3xrnRv8R13w6ttpJzvB6Y0VGJ50GylHwtBbKEzXjCIEM5qJjPXhQxEBdfeTIgK3oeUl+UdmAc4XS5eVAMThq87YTO/jwL8KNAzScmhYs=,iv:3a0Zo4XviDUECcFSfdqs1dGW9VSnSwbZD6vpduoI8lc=,tag:745ioTK2zJem0u7H/bN+XQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
