apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-import-sa
  namespace: default
  labels:
    app: email-import
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: email-import-role
  namespace: default
spec:
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: email-import-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: email-import-role
subjects:
- kind: ServiceAccount
  name: email-import-sa
  namespace: default

