apiVersion: ENC[AES256_GCM,data:NSI=,iv:RG12oXw7Fno5Ff02ZvMxyIL54H9v9h9FpD1XR6RhDbs=,tag:8M6bAIzxfs0YREbPgwgEbg==,type:str]
kind: ENC[AES256_GCM,data:5ngMtPKS,iv:lGp1cHk1N09YMPSZgg19dO81rbMEW+7og7ZBSJXUHDU=,tag:xNR58ddGXCLX/hkZkWaQjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MdfF6zV+djaAJqQXXmR/9Q==,iv:4PgKfw1w8LEHaD+nGhZyR6fL2YIWNA6g1NKDaULy93w=,tag:EY+csDLm0OMBtOtutyPu1Q==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:qBKXDvd3aMOl3XY99A7eHan5sSWo/gaxYQY0DcAHLata9j2kvHb7mgIavNFgOMj7gsckhAwZXxI64D42uWlYD+QTf1G5zhuku6CHKCPaiVPQuEmEs6UsmgS2lIfsG6AABI0AXy6dCrWa82P7RA9aU87lcroxEpR+1RoiKPRystG4gj4xfkDuRCbw0/i8oEe7vLg4Flhro6yxYFwTjcwcmMTj+WE=,iv:/D0k/QqKH7kW1Vvvz0W2Dddz51toPqTGBBJUqoWg/0U=,tag:IRonsPGrxrW9KpZ7olnj9w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:cDj/mgBuDZRB1g/RkKaxMZhCmGg52BVfRcOGopa1RXIbG5MhoSZYBlhEdDdsI4fmBUuauYI+xa7TTzd/4VH71g==,iv:9ChQTqs5nJqViV9O3gWc6Ushv2ep5Ez9RarH9Qe+5Y0=,tag:+y5tmsvWAAUpG7yBf9EoGw==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNDJpTStDSEtxOWd3eGRw
            aWhIalVGWEZqSVZ0NVBUZzNkdTFXcUIrNGdBClk1bUdaMjlmbDVDMEI5bG41bHRv
            dytwMEhiNTR3NFV2TnI2TkdCZkthY2sKLS0tIDBiQitIRytpYk1oZzFsQVk3bEpI
            cjJiV2FsVUIzY0k2TStseWRyS0tWVnMKX6/SEo8sSXbIaB6y3ILXdkRk4QFDoAqn
            trX8vg4dUpHPiXFeN5Iu5a+U16Y6yYgXdCkGsAi2QtD2N1bCWvPL5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T18:45:15Z"
    mac: ENC[AES256_GCM,data:UOwGeULXzkpgUOogA/LsPnSnXpLHhYNQTDrMS88rx7oKtQQjZUL3IHDkAEYUaACUGt7sc4X8Lweo1EyYeMQqUZcw8606N22cuNgauTC2I/Y9CjYSJRAv45jx6oj/AIVqOyBYBmr9xUsVJOKY9+V64ELlOpNYRN2WZejpY3V5DiI=,iv:wMiNIb+q2tOfVXZEXmGia/cocZI7venRNFdMKvtP/tU=,tag:NWrClgEhQ1sQKDThHqRBsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
