apiVersion: ENC[AES256_GCM,data:UF0=,iv:lv02+3Ep3OZ5txZzOE4bGF2a0cPJsCZ5ECUmTVFWvws=,tag:V3+9XCs2ebn+0TlpWE8Z1g==,type:str]
kind: ENC[AES256_GCM,data:cRGUAqD/,iv:IvNpSSd7yuxgJyhVyKv1QJInux549QAqn6RfkVPP60o=,tag:NlokOP/LSKu6ReFgN/4foA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B0BBcH35Lgr2dUEIwLdGsg==,iv:2ILB4jO55a0BXuesWxQN8IFgS0GW9PqjdW0mCfSMfw8=,tag:QPg2q4/K611PQJ9OXpPutw==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:T5YMFvbLyZ+RWrRPhfy3/s5Ej+mS/okg2I7wjcFtiVU6IG0umAiNccGXb9pRvhcKEsTj8x592tLKFC+nMff2CBeMKISMouvOyFtKc/ZxcSyuyO4Rp7+KUak0E/jVlduIFz49m/HDhoBvOYrfYnujvRLqXKTDr4txnStp7SdJW5vgbNd9uUmwaeSxQoY3IOEyF4wLiXAMWO2uoFww477RdtgQFck=,iv:SxaRksYSkc3xivxkptLfF/IuD0Nc8Pcg8DMIrIdSDtc=,tag:V0eC5bUCANYK/VQEjEDs7w==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:ua6BCy40i54kpBv2tMaZ50cQT61Ze8YEGPnP90ptW0PfkloddxKwbUt98rRRsMUOCXxyw6InKOq9ZTLyrmoAww==,iv:03k7LxbCKs4hopo2fzsw1kcp2oosRJYG2hqRwK7Qoxs=,tag:tyJNeqU0ychwT/BifjBjlA==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:i9/54FEkCOG3fqcuJvsaWSkwDSPBhjhR9eaDhAVlrlBlcLUgYm4FRwW5Y9ydK7UPdHnixME8hN1X,iv:ko/R7ajQD0Xepd9TxQWl8kbJHoqXoA4EB/1mdy1tWU8=,tag:bfc4v8Art2TYF4YQW+K25A==,type:str]
    SLACK_SIGNING_SECRET: ENC[AES256_GCM,data://LHu6rCxWJ8+RQrnglcaR1VB6RTA7mH9U6Mnps8nYw=,iv:Oy8z5ziK1YJh4q6CGr/Ni+QlVgeQJNTO+VttZoEZRkY=,tag:meOl9c0nCCvP864h8qlR/A==,type:str]
sops:
    age:
        - recipient: age103wy5wh49l0ptpscalt4ywxezd2nqykd29jru0fvgen7aweffp2s99kne9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSTJtanYzWU51RUhwRjIy
            SHdlb2dheEpmNW9jS3Q5alpJajZSdzBnSVNRCnFROG1OTUR2N3p0TkpoT1NNNVNx
            aENQTjdySW80bDZyY1RBM2krWFU5cGcKLS0tIEVldWo2czVFb0RjZ0xiaVN5OUNw
            NkNRY2lqNTFkMXdLRUNCVVYzRGgwckEK+iVip5wtQutp8G9I8aEzagDwvjQskenK
            WSA1VIh/idDJu5uNLSIRWZxAPY6zZl7PX8gVCbpPN8gOZII4vBT13Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T19:24:43Z"
    mac: ENC[AES256_GCM,data:qEVv4kX7t9NgAelVhD36buZfbKHEgkylVYB0v4JE6LYmZFXT0RESA7vbQMVDIz6yzQqB4ZJitKg6Lmrp2swnCXtmxs1Bcqppxo9Q15H2qnlU33/qqtydmqJ7Az8/53jXCmcal1hyNl9lX1AyDg6jirOuhN8UZ+krhvSeIG3mlz8=,iv:IEH4Bu+TYAqGAycR0vO38NL2WfCygcprw3I+PIdLWTs=,tag:RYknXuzi7x0oaUpeTe1Uaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
